/**
 * 每个元素的作用与生活应用。
 *
 * 由 scripts/build-data.mjs 合并进 elements.json，构建期断言 1-118 全部有条目 ——
 * 漏掉任何一个都会让构建失败，而不是在页面上留一段空白。
 *
 * `zh` / `en` 是一到两句"它有什么用"；`itemsZh` / `itemsEn` 是具体到能在生活里
 * 指认出来的东西。合成超重元素没有任何实际用途，就如实写没有，不编。
 */
/**
 * 101 号之后的元素只能在加速器里以单个原子的规模合成，半衰期通常不到一分钟，
 * 全部没有任何实际用途 —— 条目里如实写明"没有"，并各补一条值得一提的事实，
 * 而不是编造用途来把格子填满。
 */
export const ELEMENT_USES = {
  1: {
    zh: '工业上主要用来合成氨造化肥，以及在炼油中给油品加氢；也是燃料电池和火箭的燃料。',
    en: 'Mostly used to make ammonia for fertiliser and to upgrade fuels in refineries; also the fuel in fuel cells and rockets.',
    itemsZh: ['合成氨化肥', '氢燃料电池车', '石油精炼加氢', '氢化植物油'],
    itemsEn: ['Ammonia fertiliser', 'Fuel-cell vehicles', 'Oil refining', 'Hydrogenated oils'],
  },
  2: {
    zh: '沸点最低，是超导磁体唯一可行的冷却剂；化学上完全惰性，还用作保护气和深潜呼吸气。',
    en: 'Its record-low boiling point makes it the only practical coolant for superconducting magnets; being inert, it also serves as a shielding and diving gas.',
    itemsZh: ['医院 MRI 磁体冷却', '气球与飞艇', '深海潜水混合气', '半导体制造保护气'],
    itemsEn: ['Cooling MRI magnets', 'Balloons and airships', 'Deep-diving gas mixes', 'Semiconductor shielding'],
  },
  3: {
    zh: '最轻的金属，储能能力极高，几乎所有可充电设备都靠它；碳酸锂还是双相情感障碍的经典药物。',
    en: 'The lightest metal and the backbone of rechargeable energy storage; lithium carbonate is also a classic mood-stabilising drug.',
    itemsZh: ['手机与电动车锂电池', '双相障碍治疗药', '耐热玻璃陶瓷炊具', '高温润滑脂'],
    itemsEn: ['Phone and EV batteries', 'Bipolar disorder medication', 'Heat-proof glass-ceramic cookware', 'High-temperature greases'],
  },
  4: {
    zh: '又轻又硬且不产生火花，用于精密仪器与安全工具；对 X 射线几乎透明，是 X 光管的窗口材料。',
    en: 'Light, stiff and non-sparking, so it goes into precision instruments and safety tools; nearly transparent to X-rays, it forms X-ray tube windows.',
    itemsZh: ['防爆无火花扳手', 'X 光机窗口', '航天与卫星结构件', '高端扬声器振膜'],
    itemsEn: ['Non-sparking tools', 'X-ray tube windows', 'Spacecraft structures', 'High-end speaker cones'],
  },
  5: {
    zh: '硼硅玻璃耐骤冷骤热，是实验室和烤箱玻璃器皿的基础；硼还能强烈吸收中子，用于反应堆控制。',
    en: 'Borosilicate glass shrugs off thermal shock, which is why lab and oven glassware use it; boron also absorbs neutrons strongly for reactor control.',
    itemsZh: ['耐热玻璃锅具与量杯', '洗涤剂中的硼砂', '核反应堆控制棒', '玻璃纤维与农用硼肥'],
    itemsEn: ['Heat-proof glassware', 'Borax in detergents', 'Reactor control rods', 'Fibreglass and boron fertiliser'],
  },
  6: {
    zh: '所有有机物和生命的骨架元素。同一个元素能变成最软的石墨和最硬的金刚石，用途横跨整个工业。',
    en: 'The skeleton of every organic compound and of life itself. The same element gives both the softest graphite and the hardest diamond.',
    itemsZh: ['铅笔芯与电池电极（石墨）', '切割工具与首饰（金刚石）', '净水器与口罩活性炭', '碳纤维车架与球拍'],
    itemsEn: ['Pencil leads and battery electrodes', 'Cutting tools and jewellery', 'Activated carbon in filters and masks', 'Carbon-fibre frames'],
  },
  7: {
    zh: '空气的主要成分。合成氨把它变成化肥，直接支撑了全球约一半人口的粮食供给。',
    en: 'The bulk of the air. Turning it into ammonia for fertiliser underpins the food supply of roughly half the world.',
    itemsZh: ['氮肥（哈伯法）', '液氮冷冻与冷链', '食品包装充氮保鲜', '轮胎充氮'],
    itemsEn: ['Nitrogen fertiliser', 'Liquid-nitrogen freezing', 'Nitrogen-flushed food packaging', 'Tyre inflation'],
  },
  8: {
    zh: '呼吸赖以为生，也是炼钢的关键 —— 现代炼钢靠吹氧脱碳。医疗与焊接同样离不开它。',
    en: 'Essential to breathing and to steelmaking, where blowing oxygen removes carbon. Medicine and welding depend on it too.',
    itemsZh: ['医用供氧与急救', '炼钢吹氧', '氧炔焊接与切割', '污水处理曝气'],
    itemsEn: ['Medical oxygen', 'Oxygen steelmaking', 'Oxy-fuel welding', 'Wastewater aeration'],
  },
  9: {
    zh: '牙膏里的氟化物能显著防蛀；聚四氟乙烯就是不粘锅涂层。制冷剂和大量药物也含氟。',
    en: 'Fluoride in toothpaste sharply cuts tooth decay; PTFE is the non-stick coating on pans. Refrigerants and many drugs contain fluorine.',
    itemsZh: ['牙膏防蛀氟化物', '不粘锅涂层（特氟龙）', '空调冰箱制冷剂', '含氟药物与铀浓缩'],
    itemsEn: ['Fluoride toothpaste', 'Non-stick pan coatings', 'Refrigerants', 'Fluorinated drugs, uranium enrichment'],
  },
  10: {
    zh: '通电发出标志性的橙红色光，霓虹招牌因此得名；也用于高压指示灯和准分子激光。',
    en: 'Glows its signature orange-red when energised, giving neon signs their name; also used in indicator lamps and excimer lasers.',
    itemsZh: ['霓虹灯招牌', '高压电指示灯', '准分子激光器', '低温制冷剂'],
    itemsEn: ['Neon signage', 'High-voltage indicators', 'Excimer lasers', 'Cryogenic refrigerant'],
  },
  11: {
    zh: '以食盐形式进入每一餐，也是人体神经传导必需的电解质；工业上制烧碱、小苏打和路灯。',
    en: 'Reaches every meal as table salt and carries nerve impulses in the body; industrially it makes caustic soda, baking soda and street lamps.',
    itemsZh: ['食盐与人体电解质', '小苏打与烧碱', '高压钠灯路灯', '钠冷快中子堆'],
    itemsEn: ['Table salt and electrolytes', 'Baking soda and caustic soda', 'Sodium street lamps', 'Sodium-cooled reactors'],
  },
  12: {
    zh: '密度最低的结构金属，笔记本外壳和汽车轻量化都靠镁铝合金；还是叶绿素的中心原子。',
    en: 'The lightest structural metal, behind laptop shells and lightweight car parts; it also sits at the centre of every chlorophyll molecule.',
    itemsZh: ['笔记本与汽车镁合金件', '烟花与照明弹', '泻盐与抗酸胃药', '叶绿素核心'],
    itemsEn: ['Laptop and car alloy parts', 'Flares and fireworks', 'Epsom salts and antacids', 'Core of chlorophyll'],
  },
  13: {
    zh: '轻、耐蚀、可无限回收，是用量仅次于铁的金属；从易拉罐到飞机机身都是它。',
    en: 'Light, corrosion-resistant and endlessly recyclable, it is the second most-used metal after iron — from drink cans to aircraft skins.',
    itemsZh: ['易拉罐与铝箔', '门窗与幕墙', '飞机机身与轮毂', '高压输电线'],
    itemsEn: ['Cans and foil', 'Window frames and cladding', 'Aircraft bodies and wheels', 'Overhead power lines'],
  },
  14: {
    zh: '整个信息时代建立在硅晶圆上；同时以二氧化硅的形式构成玻璃、水泥和沙子。',
    en: 'The entire information age runs on silicon wafers; as silica it also makes up glass, cement and sand.',
    itemsZh: ['芯片与集成电路', '太阳能电池板', '玻璃与水泥', '硅胶密封与干燥剂'],
    itemsEn: ['Computer chips', 'Solar panels', 'Glass and cement', 'Silicone sealants, silica gel'],
  },
  15: {
    zh: '生命的能量货币 ATP 和 DNA 骨架都含磷；农业上是三大肥料元素之一，缺它作物无法生长。',
    en: 'Phosphorus is in ATP and the DNA backbone; in farming it is one of the three primary fertiliser nutrients no crop can do without.',
    itemsZh: ['磷肥', '火柴头', 'DNA 与 ATP', '阻燃剂与洗涤剂'],
    itemsEn: ['Phosphate fertiliser', 'Match heads', 'DNA and ATP', 'Flame retardants, detergents'],
  },
  16: {
    zh: '硫酸产量常被用作衡量一国工业规模的指标；橡胶硫化让轮胎从黏软变得坚韧耐磨。',
    en: 'Sulfuric acid output is a classic yardstick of industrial scale; vulcanisation with sulfur turns sticky rubber into tough tyre tread.',
    itemsZh: ['硫酸（工业之母）', '轮胎橡胶硫化', '火药与烟花', '农药杀菌与葡萄园'],
    itemsEn: ['Sulfuric acid', 'Vulcanised rubber tyres', 'Gunpowder', 'Fungicides in vineyards'],
  },
  17: {
    zh: '自来水消毒每年避免大量水源性疾病，是公共卫生史上最重要的措施之一；也是 PVC 塑料的原料。',
    en: 'Chlorinating drinking water prevents enormous numbers of waterborne illnesses, one of the great public-health advances; it also makes PVC.',
    itemsZh: ['自来水与泳池消毒', '84 消毒液与漂白剂', 'PVC 管材与地板', '盐酸'],
    itemsEn: ['Water and pool disinfection', 'Bleach', 'PVC pipes and flooring', 'Hydrochloric acid'],
  },
  18: {
    zh: '空气中含量第三的气体，便宜又惰性，是焊接时隔绝氧气的首选保护气；也灌进中空玻璃隔热。',
    en: 'The third most common gas in air: cheap and inert, it is the default shielding gas for welding and the fill in insulated glazing.',
    itemsZh: ['氩弧焊保护气', '中空玻璃填充', '灯泡与荧光灯填充', '金属冶炼保护气氛'],
    itemsEn: ['Arc-welding shielding gas', 'Insulated window glazing', 'Lamp fill gas', 'Metallurgical blanketing'],
  },
  19: {
    zh: '与钠共同维持细胞内外的电位差，心跳和神经信号都依赖它；农业上是三大肥料元素之一。',
    en: 'With sodium it maintains the voltage across cell membranes that drives heartbeats and nerve signals; also a primary fertiliser nutrient.',
    itemsZh: ['钾肥', '香蕉等食物中的电解质', '硝石（黑火药）', '软肥皂与玻璃'],
    itemsEn: ['Potash fertiliser', 'Dietary electrolyte', 'Saltpetre in gunpowder', 'Soft soaps and glass'],
  },
  20: {
    zh: '骨骼和牙齿的主要成分；以石灰和水泥的形式，也是人类用量最大的建筑材料基础。',
    en: 'The main mineral in bones and teeth, and — as lime and cement — the basis of the most heavily used building material on Earth.',
    itemsZh: ['骨骼与牙齿', '水泥与石灰', '钙片与牛奶', '豆腐凝固剂、烟气脱硫'],
    itemsEn: ['Bones and teeth', 'Cement and lime', 'Calcium supplements', 'Tofu coagulant, flue-gas desulfurisation'],
  },
  21: {
    zh: '加进铝里能显著提高强度而几乎不增重，用于高端自行车架、棒球棒和航空部件。',
    en: 'A little scandium makes aluminium far stronger at almost no weight cost, hence its use in high-end bike frames, bats and aerospace parts.',
    itemsZh: ['铝钪合金自行车架', '棒球棒与航空件', '金属卤化物灯', '固体氧化物燃料电池'],
    itemsEn: ['Al-Sc bicycle frames', 'Baseball bats, aerospace parts', 'Metal-halide lamps', 'Solid-oxide fuel cells'],
  },
  22: {
    zh: '强度接近钢却轻得多，且与人体组织相容，是人工关节和牙种植体的标准材料。',
    en: 'Nearly as strong as steel but far lighter, and biocompatible — the standard material for joint replacements and dental implants.',
    itemsZh: ['人工关节与牙种植体', '飞机发动机与机体', '钛白粉（涂料、防晒霜）', '眼镜架与高端表壳'],
    itemsEn: ['Joint and dental implants', 'Jet engines and airframes', 'Titanium dioxide in paint and sunscreen', 'Eyeglass frames'],
  },
  23: {
    zh: '少量钒就能让钢的强度和韧性大幅提升，扳手、弹簧和工具钢都靠它；也用于大规模储能电池。',
    en: 'A trace of vanadium greatly toughens steel — spanners, springs and tool steels rely on it; it also powers grid-scale flow batteries.',
    itemsZh: ['铬钒钢工具与扳手', '弹簧与轴承钢', '钒液流储能电池', '制硫酸催化剂'],
    itemsEn: ['Chrome-vanadium tools', 'Springs and bearing steels', 'Vanadium flow batteries', 'Sulfuric acid catalyst'],
  },
  24: {
    zh: '不锈钢之所以不锈，靠的就是铬在表面自发形成的致密氧化膜；电镀铬则提供镜面般的耐磨层。',
    en: 'Stainless steel resists rust because chromium forms a dense self-healing oxide film; chrome plating adds a mirror-hard wear layer.',
    itemsZh: ['不锈钢餐具与厨具', '水龙头与汽车镀铬件', '皮革鞣制', '颜料与耐火砖'],
    itemsEn: ['Stainless cutlery and cookware', 'Chrome-plated fittings', 'Leather tanning', 'Pigments and refractory bricks'],
  },
  25: {
    zh: '炼钢时脱氧去硫，几乎所有钢材都含锰；高锰钢极耐冲击磨损，用于铁轨和挖掘机斗齿。',
    en: 'Removes oxygen and sulfur during steelmaking, so nearly all steel contains it; high-manganese steel resists battering, as in rails and digger teeth.',
    itemsZh: ['钢铁脱氧与高锰钢铁轨', '干电池正极', '高锰酸钾消毒', '铝合金与玻璃脱色'],
    itemsEn: ['Steelmaking and rail steel', 'Dry-cell battery cathodes', 'Potassium permanganate disinfectant', 'Aluminium alloys'],
  },
  26: {
    zh: '人类用量最大的金属，钢铁撑起了建筑、桥梁、汽车和铁路；在体内则是血红蛋白运氧的核心。',
    en: 'The most used metal on Earth: steel holds up buildings, bridges, cars and railways, while in the body iron is what carries oxygen in haemoglobin.',
    itemsZh: ['钢筋、桥梁与汽车', '血红蛋白运氧', '永磁体与变压器铁芯', '补铁剂与铁强化食品'],
    itemsEn: ['Rebar, bridges and cars', 'Haemoglobin', 'Magnets and transformer cores', 'Iron supplements'],
  },
  27: {
    zh: '锂电池正极的关键成分，也是维生素 B12 的中心原子；钴蓝自古就是最珍贵的蓝色颜料。',
    en: 'A key ingredient of lithium-battery cathodes and the atom at the centre of vitamin B12; cobalt blue has been a prized pigment for centuries.',
    itemsZh: ['锂电池正极材料', '维生素 B12', '钴蓝玻璃与陶瓷釉', '超硬合金刀具、钴 60 放疗'],
    itemsEn: ['Lithium-battery cathodes', 'Vitamin B12', 'Cobalt-blue glass and glazes', 'Carbide tools, Co-60 radiotherapy'],
  },
  28: {
    zh: '不锈钢里的镍决定了它的韧性和耐蚀性；镍还广泛用于电镀、硬币和充电电池。',
    en: 'Nickel gives stainless steel its toughness and corrosion resistance, and also goes into plating, coins and rechargeable batteries.',
    itemsZh: ['不锈钢与耐蚀合金', '镍氢/锂电池材料', '硬币与电镀层', '人造奶油氢化催化剂'],
    itemsEn: ['Stainless and corrosion-resistant alloys', 'NiMH and Li-ion batteries', 'Coins and plating', 'Hydrogenation catalyst'],
  },
  29: {
    zh: '导电性仅次于银而便宜得多，几乎所有电线和电路板都用铜；表面还能持续杀灭细菌。',
    en: 'Second only to silver in conductivity but far cheaper, copper carries almost all electrical wiring; its surfaces also keep killing bacteria.',
    itemsZh: ['电线电缆与电路板', '自来水管与暖气管', '黄铜与青铜器件', '医院抗菌门把手'],
    itemsEn: ['Wiring and circuit boards', 'Plumbing pipes', 'Brass and bronze fittings', 'Antimicrobial door handles'],
  },
  30: {
    zh: '镀锌是最经济有效的钢铁防锈手段，路灯杆和护栏都靠它；氧化锌还是物理防晒霜的主力成分。',
    en: 'Galvanising is the cheapest effective way to stop steel rusting — lamp posts and guardrails rely on it; zinc oxide is the workhorse of mineral sunscreen.',
    itemsZh: ['镀锌钢材防锈', '物理防晒霜与痱子粉', '黄铜', '锌补充剂与干电池'],
    itemsEn: ['Galvanised steel', 'Mineral sunscreen and calamine', 'Brass', 'Zinc supplements and batteries'],
  },
  31: {
    zh: '氮化镓充电器之所以能做得又小又凉，就是因为镓基半导体损耗低；蓝光 LED 也是氮化镓做的。',
    en: 'GaN chargers are small and cool because gallium semiconductors waste little energy as heat; blue LEDs are gallium nitride too.',
    itemsZh: ['氮化镓快充充电器', '蓝光与白光 LED', '手机射频芯片', '镓铟合金替代水银温度计'],
    itemsEn: ['GaN fast chargers', 'Blue and white LEDs', 'Phone RF chips', 'Mercury-free thermometers'],
  },
  32: {
    zh: '对红外线高度透明，是热成像和夜视镜头的标准材料；光纤中也靠掺锗调节折射率。',
    en: 'Highly transparent to infrared, germanium is the standard lens material for thermal imaging and night vision; it also tunes optical-fibre cores.',
    itemsZh: ['热成像与夜视镜头', '光纤芯掺杂', '红外光学窗口', 'PET 塑料聚合催化剂'],
    itemsEn: ['Thermal-imaging lenses', 'Optical-fibre doping', 'Infrared windows', 'PET plastic catalyst'],
  },
  33: {
    zh: '砷化镓芯片比硅更快更省电，手机射频前端普遍采用；三氧化二砷则是治疗白血病的有效药物。',
    en: 'Gallium-arsenide chips are faster and more efficient than silicon, common in phone radio front-ends; arsenic trioxide treats leukaemia.',
    itemsZh: ['砷化镓射频芯片', '高效太阳能电池', '白血病治疗药物', '曾用于木材防腐（现受限）'],
    itemsEn: ['GaAs radio chips', 'High-efficiency solar cells', 'Leukaemia medication', 'Formerly wood preservative'],
  },
  34: {
    zh: '人体必需的微量元素，是抗氧化酶的活性中心；二硫化硒还是去屑洗发水的有效成分。',
    en: 'An essential trace nutrient at the active site of antioxidant enzymes; selenium sulfide is the active ingredient in anti-dandruff shampoo.',
    itemsZh: ['抗氧化营养素', '去屑洗发水', '玻璃脱色与红色玻璃', '复印机与激光打印感光鼓'],
    itemsEn: ['Antioxidant nutrient', 'Anti-dandruff shampoo', 'Glass decolouriser and red glass', 'Photocopier drums'],
  },
  35: {
    zh: '溴系阻燃剂曾广泛用于电子外壳和家具泡沫；溴化银则是胶片摄影的感光核心。',
    en: 'Brominated flame retardants were widespread in electronics casings and furniture foam; silver bromide is what made photographic film sensitive to light.',
    itemsZh: ['阻燃剂', '胶片摄影感光材料', '泳池消毒剂', '镇静与抗癫痫药（历史）'],
    itemsEn: ['Flame retardants', 'Photographic film', 'Pool sanitisers', 'Historic sedatives'],
  },
  36: {
    zh: '比氩更重更惰性，灌进白炽灯能延长寿命、提高亮度；也用于高性能中空玻璃和摄影闪光灯。',
    en: 'Heavier and more inert than argon, it extends filament life and brightness in lamps, and fills premium insulated glazing and photo flash tubes.',
    itemsZh: ['高效白炽灯与闪光灯', '高性能中空玻璃', '氪激光器', '高速摄影光源'],
    itemsEn: ['Efficient lamps and flash tubes', 'Premium insulated glazing', 'Krypton lasers', 'High-speed photography'],
  },
  37: {
    zh: '铷原子钟精度极高、成本远低于铯钟，广泛用于通信基站和卫星导航的时间同步。',
    en: 'Rubidium clocks are very accurate but far cheaper than caesium ones, so they synchronise mobile networks and navigation satellites.',
    itemsZh: ['铷原子钟与基站授时', '真空管吸气剂', '光电倍增管', '冷原子物理研究'],
    itemsEn: ['Rubidium atomic clocks', 'Vacuum-tube getters', 'Photomultiplier tubes', 'Cold-atom research'],
  },
  38: {
    zh: '烟花里那抹鲜艳的红色就是锶发出的；含锶牙膏则能封闭牙本质小管，缓解牙齿敏感。',
    en: 'The vivid red in fireworks is strontium; strontium toothpaste seals dentine tubules to relieve sensitive teeth.',
    itemsZh: ['烟花与信号弹的红色', '抗敏感牙膏', '老式显像管玻璃', '铁氧体永磁'],
    itemsEn: ['Red in fireworks', 'Sensitivity toothpaste', 'CRT glass', 'Ferrite magnets'],
  },
  39: {
    zh: '白光 LED 的黄色荧光粉以钇为基础 —— 蓝光芯片加这层荧光粉才变成白光；也用于 YAG 激光。',
    en: 'The yellow phosphor in white LEDs is yttrium-based: it converts a blue chip into white light. Yttrium also forms YAG laser crystals.',
    itemsZh: ['白光 LED 荧光粉', 'YAG 激光器', '氧化锆陶瓷刀稳定剂', '高温超导材料'],
    itemsEn: ['White-LED phosphor', 'YAG lasers', 'Stabiliser in zirconia ceramics', 'High-temperature superconductors'],
  },
  40: {
    zh: '几乎不吸收中子又耐高温高压，是核燃料棒包壳的唯一选择；氧化锆陶瓷则做成牙冠和陶瓷刀。',
    en: 'Almost transparent to neutrons and tough at temperature, zirconium is the only practical cladding for nuclear fuel rods; zirconia becomes dental crowns and ceramic knives.',
    itemsZh: ['核燃料棒包壳', '氧化锆牙冠与陶瓷刀', '止汗剂有效成分', '耐火材料与铸造砂'],
    itemsEn: ['Nuclear fuel cladding', 'Zirconia crowns and ceramic knives', 'Antiperspirant actives', 'Refractories'],
  },
  41: {
    zh: '铌钛超导线是 MRI 和粒子加速器磁体的标准材料；微量铌还能让管线钢更强更韧。',
    en: 'Niobium-titanium superconducting wire is the standard for MRI and accelerator magnets; a trace of niobium also strengthens pipeline steel.',
    itemsZh: ['MRI 与加速器超导磁体', '高强度管线钢', '电容器与首饰', '喷气发动机超合金'],
    itemsEn: ['MRI and accelerator magnets', 'Pipeline steel', 'Capacitors and jewellery', 'Jet-engine superalloys'],
  },
  42: {
    zh: '含钼钢在高温下仍保持强度，用于刀具、钻头和高压管道；二硫化钼是耐极压的固体润滑剂。',
    en: 'Molybdenum steel keeps its strength when hot, so it goes into cutters, drills and high-pressure piping; molybdenum disulfide is an extreme-pressure solid lubricant.',
    itemsZh: ['高速钢刀具与钻头', '二硫化钼润滑剂', '石油脱硫催化剂', '植物必需微量元素'],
    itemsEn: ['High-speed steel tools', 'MoS2 lubricants', 'Fuel desulfurisation catalyst', 'Essential plant nutrient'],
  },
  43: {
    zh: '第一个人工合成的元素。锝 99m 是全世界使用最多的医用放射性同位素，每年数千万次显像检查靠它。',
    en: 'The first artificially made element. Technetium-99m is the most-used medical radioisotope in the world, behind tens of millions of scans a year.',
    itemsZh: ['核医学显像（骨扫描、心肌灌注）', '甲状腺与肾功能检查', '工业示踪'],
    itemsEn: ['Nuclear medicine imaging', 'Thyroid and kidney scans', 'Industrial tracing'],
  },
  44: {
    zh: '硬盘盘片中的钌薄层让磁记录密度大幅提升；也是电接触材料和多种工业催化剂的成分。',
    en: 'A thin ruthenium layer in hard-disk platters greatly raised recording density; it also serves in electrical contacts and industrial catalysts.',
    itemsZh: ['硬盘磁记录层', '电子接触与电阻', '合成氨与制氢催化剂', '耐磨钢笔尖'],
    itemsEn: ['Hard-disk recording layers', 'Electrical contacts', 'Ammonia and hydrogen catalysts', 'Wear-resistant pen nibs'],
  },
  45: {
    zh: '汽车三元催化器中最关键的一种金属，专门负责把氮氧化物还原成氮气，价格因此常年居高。',
    en: 'The single most critical metal in a catalytic converter, responsible for reducing nitrogen oxides back to nitrogen — which keeps its price extreme.',
    itemsZh: ['汽车三元催化器', '白金首饰的镀层', '玻璃纤维成型模具', '工业催化剂'],
    itemsEn: ['Catalytic converters', 'Plating on white-gold jewellery', 'Glass-fibre bushings', 'Industrial catalysts'],
  },
  46: {
    zh: '能吸收自身体积数百倍的氢气，用于氢气提纯；也是汽车催化器和手机陶瓷电容的关键材料。',
    en: 'Absorbs hundreds of times its own volume in hydrogen, so it purifies hydrogen gas; it also goes into catalytic converters and phone capacitors.',
    itemsZh: ['汽车尾气催化器', '手机中的陶瓷电容', '氢气提纯与储存', '牙科合金与首饰'],
    itemsEn: ['Catalytic converters', 'Ceramic capacitors in phones', 'Hydrogen purification', 'Dental alloys and jewellery'],
  },
  47: {
    zh: '导电导热性能均居所有金属之首，太阳能电池板正面的细密银浆栅线就是靠它导出电流；还有强抗菌性。',
    en: 'The best electrical and thermal conductor of all metals — the fine silver grid on a solar panel collects its current — and a strong antimicrobial.',
    itemsZh: ['太阳能电池银浆', '首饰与餐具', '抗菌敷料与伤口膏', '电子触点与胶片摄影'],
    itemsEn: ['Solar-cell silver paste', 'Jewellery and tableware', 'Antimicrobial dressings', 'Contacts and film photography'],
  },
  48: {
    zh: '镉黄、镉红是画家钟爱的鲜艳颜料；但镉毒性高且在体内蓄积，电池和电镀用途已大幅受限。',
    en: 'Cadmium yellow and red are prized artists’ pigments, but cadmium is toxic and accumulates in the body, so battery and plating uses are now heavily restricted.',
    itemsZh: ['镉黄/镉红颜料', '镍镉电池（淘汰中）', '量子点显示材料', '核反应堆控制棒'],
    itemsEn: ['Cadmium pigments', 'NiCd batteries (phasing out)', 'Quantum-dot displays', 'Reactor control rods'],
  },
  49: {
    zh: '氧化铟锡（ITO）既导电又透明，是所有触摸屏和液晶面板必需的透明电极，几乎无可替代。',
    en: 'Indium tin oxide is both conductive and transparent, making it the near-irreplaceable electrode layer in every touchscreen and LCD panel.',
    itemsZh: ['触摸屏与液晶透明电极', '低熔点合金与保险丝', '半导体与 LED', '真空密封垫'],
    itemsEn: ['Touchscreen and LCD electrodes', 'Low-melting alloys and fuses', 'Semiconductors and LEDs', 'Vacuum seals'],
  },
  50: {
    zh: '熔点低又不易氧化，是电子焊锡的主角；镀在钢罐内壁就成了马口铁，用于食品罐头。',
    en: 'Low-melting and slow to oxidise, tin is the basis of electronic solder; plated inside steel cans it becomes tinplate for food.',
    itemsZh: ['电子焊锡', '马口铁食品罐头', '青铜器与乐器', 'PVC 塑料稳定剂'],
    itemsEn: ['Electronic solder', 'Tinplate food cans', 'Bronze and instruments', 'PVC stabilisers'],
  },
  51: {
    zh: '三氧化二锑是应用最广的阻燃增效剂，与溴系阻燃剂配合用于电视外壳和线缆；也用于铅酸电池板栅。',
    en: 'Antimony trioxide is the most widely used flame-retardant synergist, paired with bromine compounds in TV housings and cable insulation.',
    itemsZh: ['阻燃剂增效成分', '铅酸电池板栅', '半导体与红外探测器', '玻璃与陶瓷澄清剂'],
    itemsEn: ['Flame-retardant synergist', 'Lead-acid battery grids', 'Semiconductors and IR detectors', 'Glass fining agent'],
  },
  52: {
    zh: '碲化镉薄膜太阳能电池成本低、弱光发电好，是大型光伏电站的重要技术路线；碲化铋则用于制冷片。',
    en: 'Cadmium-telluride thin-film panels are cheap and perform well in weak light, a major utility-solar technology; bismuth telluride drives Peltier coolers.',
    itemsZh: ['碲化镉薄膜太阳能', '半导体制冷片（车载冰箱）', '易切削钢添加剂', '可录光盘记录层'],
    itemsEn: ['CdTe thin-film solar', 'Peltier cooling modules', 'Free-machining steel', 'Rewritable optical discs'],
  },
  53: {
    zh: '缺碘会导致甲状腺肿和儿童智力发育障碍，食盐加碘是覆盖人口最广的公共营养干预之一。',
    en: 'Iodine deficiency causes goitre and impaired child development, so salt iodisation is one of the widest-reaching public-nutrition measures ever.',
    itemsZh: ['碘盐防治甲状腺疾病', '碘伏与碘酒消毒', 'X 光造影剂', '碘钨灯'],
    itemsEn: ['Iodised salt', 'Povidone-iodine antiseptic', 'X-ray contrast agents', 'Tungsten-halogen lamps'],
  },
  54: {
    zh: '氙气大灯亮度接近日光且更省电；氙还是效率极高的太空离子推进剂，多个探测器靠它飞行。',
    en: 'Xenon headlamps approach daylight colour at lower power; xenon is also a highly efficient ion-thruster propellant used by deep-space probes.',
    itemsZh: ['汽车氙气大灯', '摄影闪光灯与影院灯', '卫星与探测器离子推进', '吸入式麻醉与医学成像'],
    itemsEn: ['Xenon headlamps', 'Flash and cinema lamps', 'Ion thrusters', 'Anaesthesia and imaging'],
  },
  55: {
    zh: '"秒"的国际定义就建立在铯 133 原子的跃迁频率上 —— 全球时间标准和 GPS 都以铯钟为基准。',
    en: 'The SI second is defined by a transition in caesium-133: caesium clocks are the reference for world time and for GPS.',
    itemsZh: ['铯原子钟（秒的定义）', 'GPS 与电网授时', '石油钻井高密度钻井液', '光电与离子推进'],
    itemsEn: ['Caesium atomic clocks', 'GPS and grid timing', 'High-density drilling fluids', 'Photocells and ion drives'],
  },
  56: {
    zh: '硫酸钡不溶且不被吸收，喝下去能让消化道在 X 光下清晰显影，就是俗称的"钡餐"。',
    en: 'Barium sulfate is insoluble and unabsorbed, so drinking it outlines the digestive tract on X-rays — the familiar barium meal.',
    itemsZh: ['钡餐消化道造影', '石油钻井泥浆加重剂', '烟花的绿色', '玻璃与陶瓷釉'],
    itemsEn: ['Barium meal imaging', 'Drilling-mud weighting', 'Green in fireworks', 'Glass and glazes'],
  },
  57: {
    zh: '镍氢电池的负极合金以镧为主，混合动力车电池长期依赖它；高折射率镧玻璃则用于相机镜头。',
    en: 'The negative electrode of NiMH batteries is a lanthanum alloy long relied on by hybrid cars; high-index lanthanum glass goes into camera lenses.',
    itemsZh: ['镍氢电池负极合金', '相机与望远镜镜头玻璃', '石油催化裂化', '打火石合金'],
    itemsEn: ['NiMH battery electrodes', 'Camera lens glass', 'Fluid catalytic cracking', 'Lighter flints'],
  },
  58: {
    zh: '储量最丰富的稀土。二氧化铈是玻璃抛光的行业标准，手机屏幕和镜片抛光几乎都用它。',
    en: 'The most abundant rare earth. Cerium oxide is the industry standard glass polish, used on nearly every phone screen and lens.',
    itemsZh: ['玻璃与屏幕抛光粉', '汽车尾气催化储氧', '自清洁烤箱涂层', '打火石与防紫外玻璃'],
    itemsEn: ['Glass and screen polishing', 'Oxygen storage in catalytic converters', 'Self-cleaning oven coatings', 'Flints and UV-blocking glass'],
  },
  59: {
    zh: '掺镨的玻璃能滤掉钠光的强黄光，是焊工和玻璃工护目镜的标准材料；也用于强永磁体。',
    en: 'Praseodymium glass filters out the intense yellow of sodium light, the standard for welders’ and glassblowers’ goggles; it also strengthens magnets.',
    itemsZh: ['焊工与玻璃工护目镜', '钕镨永磁体', '玻璃与陶瓷黄绿着色', '光纤放大器'],
    itemsEn: ['Welding and glassblowing goggles', 'Nd-Pr magnets', 'Yellow-green glass colourant', 'Fibre amplifiers'],
  },
  60: {
    zh: '钕铁硼是目前最强的永磁体，让耳机、硬盘、电动车电机和风力发电机得以做小做强 —— 现代生活到处是它。',
    en: 'Neodymium-iron-boron is the strongest permanent magnet available, which is why headphones, hard drives, EV motors and wind turbines could shrink and get stronger.',
    itemsZh: ['耳机与扬声器磁体', '电动车驱动电机', '风力发电机', '硬盘音圈与磁力扣'],
    itemsEn: ['Headphone and speaker magnets', 'EV traction motors', 'Wind turbines', 'Hard drives and magnetic catches'],
  },
  61: {
    zh: '唯一没有稳定同位素的轻稀土，自然界几乎不存在。曾用于夜光表盘，现主要作核电池和厚度计。',
    en: 'The only light rare earth with no stable isotope, essentially absent in nature. Once used in luminous dials, now mainly in nuclear batteries and thickness gauges.',
    itemsZh: ['核电池（航天与心脏起搏器研究）', '厚度测量仪', '夜光涂料（历史用途）'],
    itemsEn: ['Nuclear batteries', 'Thickness gauges', 'Luminous paint (historic)'],
  },
  62: {
    zh: '钐钴磁体在 300 ℃ 以上仍不退磁，用于航空航天和军用电机等钕磁体扛不住的高温场合。',
    en: 'Samarium-cobalt magnets keep their strength above 300 °C, serving aerospace and military motors where neodymium magnets would fail.',
    itemsZh: ['耐高温钐钴磁体', '骨癌骨转移止痛放射药', '核反应堆中子吸收', '航空电机与传感器'],
    itemsEn: ['High-temperature SmCo magnets', 'Bone-cancer pain radiotherapy', 'Neutron absorption', 'Aerospace motors'],
  },
  63: {
    zh: '发光效率极高的红色与蓝色荧光粉基础，彩色显示和节能灯的色彩靠它；欧元纸币的防伪荧光也含铕。',
    en: 'The basis of highly efficient red and blue phosphors behind colour displays and energy-saving lamps; euro banknotes use europium in their anti-counterfeiting glow.',
    itemsZh: ['显示器与节能灯红蓝荧光粉', '欧元纸币防伪', 'LED 照明显色', '核反应堆控制'],
    itemsEn: ['Red and blue display phosphors', 'Euro banknote security', 'LED colour rendering', 'Reactor control'],
  },
  64: {
    zh: '钆的顺磁性极强，注射钆造影剂能让 MRI 中的血管和病灶大幅提高对比度，是临床最常用的 MRI 造影剂。',
    en: 'Gadolinium is strongly paramagnetic, so injected gadolinium contrast sharply increases vessel and lesion contrast in MRI — the standard clinical agent.',
    itemsZh: ['MRI 造影剂', '中子屏蔽与反应堆控制', '磁制冷技术', '绿色荧光粉与 X 光增感屏'],
    itemsEn: ['MRI contrast agents', 'Neutron shielding', 'Magnetic refrigeration', 'Green phosphors and X-ray screens'],
  },
  65: {
    zh: '三基色荧光灯里的绿色成分主要来自铽；铽合金还有极强的磁致伸缩效应，用于声呐和精密驱动器。',
    en: 'The green component of tri-phosphor lamps comes mainly from terbium; terbium alloys are strongly magnetostrictive, used in sonar and precision actuators.',
    itemsZh: ['荧光灯与显示器绿色荧光粉', '声呐磁致伸缩换能器', '磁光存储介质', '固态照明'],
    itemsEn: ['Green lamp and display phosphors', 'Sonar transducers', 'Magneto-optical storage', 'Solid-state lighting'],
  },
  66: {
    zh: '给钕磁体加镝能显著提高耐热性，电动车电机和风机在高温下不退磁全靠它 —— 也是最紧缺的稀土之一。',
    en: 'Adding dysprosium lets neodymium magnets survive heat, which is what keeps EV motors and turbines from demagnetising — and makes it one of the scarcest rare earths.',
    itemsZh: ['电动车与风机磁体耐热添加', '核反应堆控制棒', '磁致伸缩材料', '高强度激光材料'],
    itemsEn: ['Heat-resistant EV and turbine magnets', 'Reactor control rods', 'Magnetostrictive materials', 'Laser materials'],
  },
  67: {
    zh: '钬激光能在水中高效切割软组织，是碎肾结石和前列腺微创手术的主流器械。',
    en: 'Holmium lasers cut soft tissue efficiently in water, making them the mainstream tool for kidney-stone lithotripsy and prostate surgery.',
    itemsZh: ['钬激光碎石与前列腺手术', '磁体磁极片（磁矩最强）', '玻璃与立方氧化锆着色', '核反应堆控制'],
    itemsEn: ['Holmium laser surgery', 'Magnetic pole pieces', 'Glass and cubic-zirconia colouring', 'Reactor control'],
  },
  68: {
    zh: '掺铒光纤放大器让光信号无需转成电信号就能直接放大，是跨洋海底光缆和整个互联网骨干的基础。',
    en: 'Erbium-doped fibre amplifiers boost light without converting it to electricity — the foundation of transoceanic cables and the internet backbone.',
    itemsZh: ['光纤放大器（互联网骨干）', '铒激光皮肤与牙科治疗', '粉红色玻璃与釉', '核燃料控制'],
    itemsEn: ['Fibre amplifiers', 'Erbium lasers in dermatology and dentistry', 'Pink glass and glazes', 'Nuclear fuel control'],
  },
  69: {
    zh: '最稀有的稳定稀土之一。铥同位素做成便携式 X 射线源，无需电源即可在野外和战地拍片。',
    en: 'Among the rarest stable rare earths. A thulium isotope makes portable X-ray sources that need no power supply, usable in the field.',
    itemsZh: ['便携式 X 射线源', '铥激光外科手术', '高温超导材料', '激光测距'],
    itemsEn: ['Portable X-ray sources', 'Thulium laser surgery', 'High-temperature superconductors', 'Laser rangefinding'],
  },
  70: {
    zh: '掺镱光纤激光器电光转换效率极高，已成为工业金属切割和焊接的主力设备；也用于最精确的原子钟。',
    en: 'Ytterbium fibre lasers convert electricity to light with exceptional efficiency and now dominate industrial metal cutting and welding; they also drive the most accurate atomic clocks.',
    itemsZh: ['光纤激光切割与焊接', '光晶格原子钟', '地震与地质应变计', '不锈钢晶粒细化'],
    itemsEn: ['Fibre-laser cutting and welding', 'Optical-lattice clocks', 'Geological strain gauges', 'Stainless-steel refining'],
  },
  71: {
    zh: '硅酸镥晶体探测伽马射线又快又灵敏，是 PET 扫描仪的核心探测材料；镥 177 则用于靶向放疗。',
    en: 'Lutetium silicate crystals detect gamma rays fast and sensitively, forming the detector core of PET scanners; lutetium-177 is used in targeted radiotherapy.',
    itemsZh: ['PET 扫描探测晶体', '前列腺癌靶向放疗', '石油裂化催化剂', '发光二极管材料'],
    itemsEn: ['PET scanner crystals', 'Targeted cancer radiotherapy', 'Petroleum cracking catalysts', 'LED materials'],
  },
  72: {
    zh: '二氧化铪的高介电常数让晶体管在纳米尺度下不再漏电，是 45 纳米以下芯片能继续微缩的关键材料。',
    en: 'Hafnium oxide’s high dielectric constant stopped nanoscale transistors from leaking, the key that let chips keep shrinking below 45 nm.',
    itemsZh: ['芯片高 k 栅介质', '核反应堆控制棒', '等离子切割电极', '喷气发动机超合金'],
    itemsEn: ['High-k gate dielectrics in chips', 'Reactor control rods', 'Plasma-cutting electrodes', 'Jet-engine superalloys'],
  },
  73: {
    zh: '钽电容体积小、容量大、性能稳定，是手机和笔记本主板上的常客；钽还与人体高度相容，用于骨科植入。',
    en: 'Tantalum capacitors pack high capacitance into a tiny stable package, a fixture on phone and laptop boards; tantalum is also highly biocompatible for implants.',
    itemsZh: ['手机与电脑钽电容', '骨科与颅骨修复植入物', '化工耐腐蚀反应器', '硬质合金刀具'],
    itemsEn: ['Tantalum capacitors', 'Orthopaedic implants', 'Corrosion-resistant reactors', 'Carbide tooling'],
  },
  74: {
    zh: '熔点是所有金属中最高的（3422 ℃）。碳化钨硬度仅次于金刚石，几乎所有金属切削刀具和钻头都用它。',
    en: 'The highest melting point of any metal (3422 °C). Tungsten carbide is second only to diamond in hardness and tips nearly every metal-cutting tool and drill bit.',
    itemsZh: ['硬质合金刀具与钻头', '白炽灯与卤素灯灯丝', '飞镖与高尔夫配重', 'X 射线管靶材'],
    itemsEn: ['Carbide tools and drill bits', 'Lamp filaments', 'Dart and golf-club weights', 'X-ray tube targets'],
  },
  75: {
    zh: '地壳中最稀有的稳定元素之一。喷气发动机最热的涡轮叶片靠含铼超合金才能在接近熔点的环境下工作。',
    en: 'One of the rarest stable elements in the crust. Rhenium superalloys let the hottest jet-engine turbine blades operate close to their melting point.',
    itemsZh: ['喷气发动机涡轮叶片', '汽油重整催化剂', '高温热电偶', '半导体与电子靶材'],
    itemsEn: ['Jet-engine turbine blades', 'Petrol reforming catalysts', 'High-temperature thermocouples', 'Electronics targets'],
  },
  76: {
    zh: '密度最大的天然元素。锇合金极耐磨，曾是高级钢笔尖和唱针的标准材料；四氧化锇是电镜染色剂。',
    en: 'The densest natural element. Osmium alloys resist wear, long the standard for fine pen nibs and record styli; osmium tetroxide stains samples for electron microscopy.',
    itemsZh: ['高级钢笔尖与唱针', '电子显微镜染色剂', '仪器轴承与触点', '耐磨合金'],
    itemsEn: ['Pen nibs and record styli', 'Electron-microscopy stain', 'Instrument pivots and contacts', 'Wear-resistant alloys'],
  },
  77: {
    zh: '铱火花塞电极极细且耐蚀，寿命可达普通火花塞数倍；地层中的铱异常还是恐龙灭绝小行星撞击的关键证据。',
    en: 'Iridium spark-plug electrodes are ultra-fine and corrosion-proof, lasting several times longer than ordinary plugs; an iridium layer in the rock record is the key evidence for the dinosaur-killing impact.',
    itemsZh: ['长寿命铱火花塞', '晶体生长坩埚', '深空探测器热源包壳', '恐龙灭绝的地质证据'],
    itemsEn: ['Long-life spark plugs', 'Crystal-growth crucibles', 'Deep-space heat-source cladding', 'The K-Pg impact marker'],
  },
  78: {
    zh: '汽车催化器中负责氧化一氧化碳和碳氢化合物；顺铂等铂类药物则是多种癌症化疗的一线方案。',
    en: 'In catalytic converters it oxidises carbon monoxide and hydrocarbons; platinum drugs such as cisplatin are front-line chemotherapy for several cancers.',
    itemsZh: ['汽车尾气催化器', '顺铂等抗癌药', '首饰与实验室器皿', '燃料电池催化剂'],
    itemsEn: ['Catalytic converters', 'Cisplatin chemotherapy', 'Jewellery and lab ware', 'Fuel-cell catalysts'],
  },
  79: {
    zh: '不氧化不变色且延展性极佳，电子接插件镀金是为了长期接触可靠；航天器也贴金膜隔绝红外辐射。',
    en: 'It never tarnishes and is extremely ductile, so connectors are gold-plated for long-term reliability; spacecraft use gold film to reflect infrared.',
    itemsZh: ['首饰与金融储备', '电子接插件镀金', '牙科修复', '航天器隔热金膜'],
    itemsEn: ['Jewellery and reserves', 'Gold-plated connectors', 'Dental restorations', 'Spacecraft thermal film'],
  },
  80: {
    zh: '唯一常温液态的金属。曾是温度计和血压计的标准，但因神经毒性正被全球逐步淘汰。',
    en: 'The only metal liquid at room temperature. Once standard in thermometers and blood-pressure cuffs, it is being phased out worldwide for its neurotoxicity.',
    itemsZh: ['温度计与血压计（淘汰中）', '荧光灯与节能灯', '牙科银汞合金', '氯碱工业电解'],
    itemsEn: ['Thermometers (being phased out)', 'Fluorescent lamps', 'Dental amalgam', 'Chlor-alkali electrolysis'],
  },
  81: {
    zh: '毒性极强，曾作鼠药和"继承粉"而臭名昭著；如今主要用于心肌灌注显像和红外光学。',
    en: 'Highly toxic and once notorious as rat poison and the "inheritance powder"; today it mainly serves cardiac perfusion imaging and infrared optics.',
    itemsZh: ['心肌灌注显像', '红外光学元件', '高温超导材料', '鼠药（已禁用）'],
    itemsEn: ['Cardiac perfusion imaging', 'Infrared optics', 'High-temperature superconductors', 'Rat poison (banned)'],
  },
  82: {
    zh: '密度大又便宜，是 X 光防护铅衣和铅板的标准材料；汽车启动电池至今仍以铅酸电池为主。',
    en: 'Dense and cheap, lead is the standard for X-ray aprons and shielding; car starter batteries are still overwhelmingly lead-acid.',
    itemsZh: ['汽车铅酸启动电池', 'X 光防护铅衣与铅玻璃', '辐射屏蔽与配重', '曾用于汽油与油漆（已禁）'],
    itemsEn: ['Lead-acid car batteries', 'X-ray shielding', 'Radiation shielding and ballast', 'Formerly in petrol and paint'],
  },
  83: {
    zh: '毒性远低于同族的铅，正在多个场合取代铅：无铅焊料、无铅子弹、渔具配重；胃药"次水杨酸铋"也是它。',
    en: 'Far less toxic than its neighbour lead and increasingly replaces it in solder, ammunition and fishing weights; bismuth subsalicylate is a common stomach remedy.',
    itemsZh: ['止泻胃药（次水杨酸铋）', '无铅焊料与子弹', '化妆品珠光颜料', '消防喷淋易熔合金'],
    itemsEn: ['Stomach remedies', 'Lead-free solder and shot', 'Pearlescent cosmetics', 'Fire-sprinkler fusible alloys'],
  },
  84: {
    zh: '放射性极强，一克钋释放的热量足以让自身炽热。曾用于消除静电的电离器，也曾是航天器热源。',
    en: 'Intensely radioactive — a gram glows from its own heat. Used in static eliminators and once as a spacecraft heat source.',
    itemsZh: ['静电消除器（工业与摄影）', '航天器热源（历史）', '中子源引发剂'],
    itemsEn: ['Static eliminators', 'Spacecraft heat sources (historic)', 'Neutron-source initiators'],
  },
  85: {
    zh: '地壳中最稀有的天然元素，全球任一时刻的总量不足一克。砹 211 正被研究用于靶向 α 放疗。',
    en: 'The rarest naturally occurring element — under a gram exists on Earth at any moment. Astatine-211 is being investigated for targeted alpha therapy.',
    itemsZh: ['靶向 α 放疗研究（癌症）'],
    itemsEn: ['Targeted alpha-therapy research'],
  },
  86: {
    zh: '从土壤渗入室内的放射性气体，是仅次于吸烟的肺癌成因，许多国家要求新建住宅做氡检测。',
    en: 'A radioactive gas seeping from soil into buildings and the second-leading cause of lung cancer, which is why many countries require radon testing in new homes.',
    itemsZh: ['室内空气污染检测对象', '地质与地震监测示踪', '放射治疗（历史用途）'],
    itemsEn: ['Indoor air-quality testing', 'Geological and seismic tracing', 'Radiotherapy (historic)'],
  },
  87: {
    zh: '天然存在量极少，半衰期仅 22 分钟，从未被大量制得。没有实际用途，仅用于原子结构研究。',
    en: 'Vanishingly rare in nature with a 22-minute half-life, never obtained in bulk. It has no practical use beyond atomic-structure research.',
    itemsZh: [],
    itemsEn: [],
  },
  88: {
    zh: '居里夫妇发现的元素。曾大量用于夜光表盘，导致"镭女郎"职业中毒事件，如今已被安全材料全面取代。',
    en: 'Discovered by the Curies and once painted on luminous watch dials, causing the "Radium Girls" poisonings; it has since been replaced entirely by safer materials.',
    itemsZh: ['夜光表盘与早期放疗（均已淘汰）', '工业射线探伤源（历史）'],
    itemsEn: ['Luminous dials and early radiotherapy (both obsolete)', 'Industrial radiography (historic)'],
  },
  89: {
    zh: '锕 225 释放的 α 粒子射程极短，能在杀死癌细胞的同时几乎不伤及周围组织，是靶向放疗的前沿药物。',
    en: 'Actinium-225 emits alpha particles with a very short range, killing cancer cells while barely touching neighbouring tissue — a frontier of targeted radiotherapy.',
    itemsZh: ['靶向 α 放疗（前列腺癌等）', '中子源'],
    itemsEn: ['Targeted alpha therapy', 'Neutron sources'],
  },
  90: {
    zh: '储量约为铀的三到四倍，且难以用于武器，钍基熔盐堆因此被视为下一代核能的重要路线之一。',
    en: 'Three to four times more abundant than uranium and hard to weaponise, which is why thorium molten-salt reactors are a leading next-generation nuclear concept.',
    itemsZh: ['钍基核燃料研究', '高折射率光学玻璃', '气灯纱罩（历史）', '高温合金与焊条'],
    itemsEn: ['Thorium fuel research', 'High-index optical glass', 'Gas-lamp mantles (historic)', 'High-temperature alloys'],
  },
  91: {
    zh: '天然存在量极微且提取困难，价格昂贵。除同位素年代测定外没有实际应用。',
    en: 'Present in nature only in traces and very hard to extract. Beyond isotope dating it has no practical application.',
    itemsZh: ['海洋沉积物年代测定'],
    itemsEn: ['Marine sediment dating'],
  },
  92: {
    zh: '核电站的燃料，全球约十分之一的电力由铀裂变提供；贫铀密度极大，用于装甲和穿甲弹。',
    en: 'The fuel of nuclear power, supplying roughly a tenth of the world’s electricity; depleted uranium is extremely dense and used in armour and penetrators.',
    itemsZh: ['核电站燃料', '核武器', '贫铀装甲与配重', '铀玻璃（历史）'],
    itemsEn: ['Nuclear power fuel', 'Nuclear weapons', 'Depleted-uranium armour and ballast', 'Uranium glass (historic)'],
  },
  93: {
    zh: '第一个超铀元素。主要作为生产钚 238 的原料，也用于探测高能中子的仪器。',
    en: 'The first transuranic element. Chiefly a feedstock for making plutonium-238, and used in high-energy neutron detectors.',
    itemsZh: ['钚 238 生产原料', '高能中子探测器'],
    itemsEn: ['Feedstock for plutonium-238', 'High-energy neutron detectors'],
  },
  94: {
    zh: '钚 238 的衰变热能稳定供电数十年，旅行者号、好奇号和毅力号等深空探测器都靠它工作。',
    en: 'The decay heat of plutonium-238 supplies steady power for decades, running Voyager, Curiosity, Perseverance and other deep-space craft.',
    itemsZh: ['深空探测器同位素电池', '核武器', '心脏起搏器电源（历史）'],
    itemsEn: ['Radioisotope power for spacecraft', 'Nuclear weapons', 'Pacemaker batteries (historic)'],
  },
  95: {
    zh: '离日常生活最近的锕系元素 —— 绝大多数离子式烟雾报警器里都有极微量的镅 241，靠它电离空气探测烟雾。',
    en: 'The actinide closest to everyday life: almost every ionisation smoke alarm contains a minute amount of americium-241, which ionises air to sense smoke.',
    itemsZh: ['离子式烟雾报警器', '厚度与密度测量仪', '中子源与石油测井'],
    itemsEn: ['Ionisation smoke alarms', 'Thickness and density gauges', 'Neutron sources and well logging'],
  },
  96: {
    zh: '火星车上的 α 粒子 X 射线谱仪用锔 244 轰击岩石以测定成分 —— 勇气号、机遇号和好奇号都带着它。',
    en: 'Mars rovers use curium-244 in their alpha-particle X-ray spectrometers to determine rock composition; Spirit, Opportunity and Curiosity all carried it.',
    itemsZh: ['火星车岩石成分分析仪', '同位素电源研究'],
    itemsEn: ['Mars rover rock analysis', 'Radioisotope power research'],
  },
  97: {
    zh: '只能在反应堆中以微克级合成。唯一实际用途是作为合成更重元素（如 117 号）的靶材。',
    en: 'Made only in microgram amounts in reactors. Its one practical use is as a target for synthesising heavier elements such as element 117.',
    itemsZh: ['合成超重元素的靶材'],
    itemsEn: ['Target material for superheavy synthesis'],
  },
  98: {
    zh: '极强的中子源，一微克每秒放出数百万个中子。用于金矿银矿勘探、反应堆启动和部分肿瘤的近距离治疗。',
    en: 'An intense neutron source — one microgram emits millions of neutrons per second. Used in gold and silver prospecting, reactor start-up and some brachytherapy.',
    itemsZh: ['便携中子源（探矿与测井）', '反应堆启动中子源', '中子俘获癌症治疗'],
    itemsEn: ['Portable neutron sources', 'Reactor start-up', 'Neutron-capture cancer therapy'],
  },
  99: {
    zh: '在首次氢弹试验的残骸中被发现。产量以微克计，除基础研究外没有应用。',
    en: 'Found in the debris of the first hydrogen bomb test. Produced in microgram quantities and used only in basic research.',
    itemsZh: [],
    itemsEn: [],
  },
  100: {
    zh: '目前只能通过中子俘获少量制得，且无法以称量级获得。仅用于核物理研究。',
    en: 'Obtainable only in tiny amounts by neutron capture and never in weighable quantities. Used only in nuclear-physics research.',
    itemsZh: [],
    itemsEn: [],
  },
  101: {
    zh: '为纪念门捷列夫命名。每次只能合成几个原子，仅用于验证锕系元素的化学行为。',
    en: 'Named for Mendeleev. Only a few atoms are made at a time, used solely to test how actinides behave chemically.',
    itemsZh: [],
    itemsEn: [],
  },
  102: {
    zh: '命名自诺贝尔。半衰期以分钟计，只能以单个原子的规模研究，没有任何实际用途。',
    en: 'Named for Nobel. With half-lives measured in minutes, it can only be studied one atom at a time and has no practical use.',
    itemsZh: [],
    itemsEn: [],
  },
  103: {
    zh: '锕系的最后一个元素。它的电子排布曾长期存疑，2015 年的实验最终确认了周期表的排布方式。',
    en: 'The last actinide. Its electron configuration was long disputed; a 2015 experiment finally settled how the periodic table should be laid out.',
    itemsZh: [],
    itemsEn: [],
  },
  104: {
    zh: '第一个超锕系元素。科学家逐个原子地研究它的化学性质，用以检验相对论效应是否会打乱周期律。',
    en: 'The first transactinide. Its chemistry is probed one atom at a time, testing whether relativistic effects break the periodic law.',
    itemsZh: [],
    itemsEn: [],
  },
  105: {
    zh: '半衰期仅数十秒。化学实验必须在合成后的几秒内完成，是「单原子化学」的极限挑战。',
    en: 'Half-lives of only tens of seconds mean chemistry must be done within seconds of synthesis — the limit of single-atom chemistry.',
    itemsZh: [],
    itemsEn: [],
  },
  106: {
    zh: '以西博格命名，是首个以在世科学家命名的元素，当时曾引发不小的争议。',
    en: 'Named for Seaborg — the first element named after a living scientist, which caused considerable controversy at the time.',
    itemsZh: [],
    itemsEn: [],
  },
  107: {
    zh: '命名自玻尔。实验证实它的化学性质与同族的铼相似，支持了周期表在超重区依然有效。',
    en: 'Named for Bohr. Experiments confirmed it behaves like its group neighbour rhenium, supporting the periodic table even among superheavy elements.',
    itemsZh: [],
    itemsEn: [],
  },
  108: {
    zh: '已知密度最大的元素（推算约 41 g/cm³）。曾成功合成四氧化物，证明它确实像同族的锇。',
    en: 'The densest element known (calculated at about 41 g/cm3). A tetroxide was successfully made, proving it really does resemble osmium.',
    itemsZh: [],
    itemsEn: [],
  },
  109: {
    zh: '命名自发现核裂变理论解释的迈特纳。至今合成总量不足百个原子。',
    en: 'Named for Lise Meitner, who explained nuclear fission. Fewer than a hundred atoms have ever been made.',
    itemsZh: [],
    itemsEn: [],
  },
  110: {
    zh: '命名自德国达姆施塔特的重离子研究所 —— 107 到 112 号元素都在那里首次合成。',
    en: 'Named for Darmstadt, Germany, where elements 107 through 112 were all first synthesised.',
    itemsZh: [],
    itemsEn: [],
  },
  111: {
    zh: '命名自 X 射线的发现者伦琴，恰好在其发现 X 射线一百周年前后被确认。',
    en: 'Named for Rontgen, discoverer of X-rays, and confirmed almost exactly a century after that discovery.',
    itemsZh: [],
    itemsEn: [],
  },
  112: {
    zh: '命名自哥白尼。理论预测它可能像汞一样具有挥发性，实验结果也支持这一点。',
    en: 'Named for Copernicus. Theory predicts it may be volatile like mercury, and experiments so far agree.',
    itemsZh: [],
    itemsEn: [],
  },
  113: {
    zh: '第一个由亚洲团队（日本理化学研究所）发现并命名的元素，名字取自日本的古称。',
    en: 'The first element discovered and named by an Asian team (RIKEN, Japan), taking its name from an old word for Japan.',
    itemsZh: [],
    itemsEn: [],
  },
  114: {
    zh: '命名自弗廖罗夫。它被认为接近理论预测的「稳定岛」—— 超重元素半衰期可能重新变长的区域。',
    en: 'Named for Flerov. It is thought to lie near the predicted island of stability, where superheavy half-lives may lengthen again.',
    itemsZh: [],
    itemsEn: [],
  },
  115: {
    zh: '命名自莫斯科州。合成它需要用钙 48 离子束轰击镅靶，持续数月才能得到几个原子。',
    en: 'Named for the Moscow region. Making it takes months of bombarding an americium target with calcium-48 to yield a handful of atoms.',
    itemsZh: [],
    itemsEn: [],
  },
  116: {
    zh: '命名自劳伦斯利弗莫尔国家实验室。半衰期仅数十毫秒，几乎在生成的瞬间就衰变。',
    en: 'Named for Lawrence Livermore National Laboratory. With half-lives of tens of milliseconds, it decays almost the instant it forms.',
    itemsZh: [],
    itemsEn: [],
  },
  117: {
    zh: '目前唯一需要专门在反应堆中培育锫靶材才能合成的元素，整个流程耗时两年以上。',
    en: 'The only element whose synthesis requires purpose-grown berkelium targets from a reactor, a pipeline taking more than two years.',
    itemsZh: [],
    itemsEn: [],
  },
  118: {
    zh: '已知最重的元素，位于周期表最后一格。虽在稀有气体列，理论却预测它可能并不惰性，甚至可能是固体。',
    en: 'The heaviest element known and the last box on the table. Despite sitting in the noble gases, theory predicts it may not be inert — and may even be a solid.',
    itemsZh: [],
    itemsEn: [],
  },
}
