/**
 * 每个分子的作用与生活应用。
 *
 * 由 scripts/build-molecules.mjs 合并进 molecules.json，构建期断言每个分子都有条目。
 * 有些分子（H₂S、NO₂、CCl₄）在生活中主要以危害或已淘汰的用途出现，就照实写，
 * 不硬凑成正面用途。
 */
export const MOLECULE_USES = {
  // ---- 单质 ----
  h2: {
    zh: '燃烧只产生水，被视为最干净的燃料；工业上大部分氢其实用于合成氨造化肥。',
    en: 'Burning it yields only water, making it the cleanest fuel; industrially, though, most hydrogen goes into ammonia for fertiliser.',
    itemsZh: ['氢燃料电池车与公交', '合成氨化肥', '火箭发动机燃料', '食用油氢化'],
    itemsEn: ['Fuel-cell cars and buses', 'Ammonia fertiliser', 'Rocket fuel', 'Hydrogenating edible oils'],
  },
  o2: {
    zh: '呼吸和燃烧都靠它。医院的供氧、炼钢的吹氧、焊枪的助燃，本质上都是同一件事。',
    en: 'Breathing and burning both need it — hospital oxygen, oxygen steelmaking and a welding torch are all the same reaction.',
    itemsZh: ['医用氧气与急救', '氧炔焊接切割', '炼钢吹氧', '污水处理曝气'],
    itemsEn: ['Medical oxygen', 'Oxy-fuel welding', 'Oxygen steelmaking', 'Wastewater aeration'],
  },
  n2: {
    zh: '化学上极不活泼，正好用来隔绝氧气：薯片袋里鼓鼓的气体就是氮气，防止油脂氧化变味。',
    en: 'Its unreactivity is the point — it keeps oxygen out. The puff of gas in a crisp packet is nitrogen, stopping the oil going rancid.',
    itemsZh: ['食品包装充氮保鲜', '液氮冷冻与冷链', '合成氨的原料', '轮胎与消防充气'],
    itemsEn: ['Nitrogen-flushed food packaging', 'Liquid-nitrogen freezing', 'Feedstock for ammonia', 'Tyre inflation'],
  },
  cl2: {
    zh: '自来水厂投氯杀菌是现代城市能大规模安全供水的前提，也是公共卫生史上最有效的措施之一。',
    en: 'Chlorinating tap water is what makes safe city-scale water supply possible, and one of the most effective public-health measures ever adopted.',
    itemsZh: ['自来水与泳池消毒', '漂白粉与漂白剂', 'PVC 塑料生产', '盐酸制造'],
    itemsEn: ['Tap-water and pool disinfection', 'Bleaching agents', 'PVC manufacture', 'Hydrochloric acid production'],
  },
  o3: {
    zh: '高空的臭氧层挡住紫外线，是地表生命的前提；地面的臭氧则用于杀菌，但吸入有害。',
    en: 'High up, the ozone layer blocks ultraviolet and makes surface life possible; at ground level it disinfects, but is harmful to breathe.',
    itemsZh: ['平流层臭氧层防紫外', '自来水臭氧消毒', '空气净化与除味', '医疗器械灭菌'],
    itemsEn: ['The stratospheric ozone layer', 'Ozone water treatment', 'Air purification', 'Medical sterilisation'],
  },
  f2: {
    zh: '本身太危险不能直接使用，但几乎所有含氟产品都由它制得 —— 从不粘锅到牙膏再到核燃料。',
    en: 'Too dangerous to handle directly, yet nearly every fluorine product starts from it — non-stick coatings, toothpaste, even nuclear fuel.',
    itemsZh: ['制备不粘锅涂层原料', '六氟化铀（铀浓缩）', '牙膏氟化物来源', '含氟制冷剂'],
    itemsEn: ['Precursor to non-stick coatings', 'Uranium hexafluoride for enrichment', 'Source of toothpaste fluoride', 'Refrigerants'],
  },
  br2: {
    zh: '溴化银对光敏感，胶片摄影的整个原理就建立在它上面；溴系阻燃剂则曾遍布电子产品外壳。',
    en: 'Silver bromide is light-sensitive, which is the entire basis of film photography; brominated flame retardants were once everywhere in electronics.',
    itemsZh: ['胶片与相纸感光材料', '阻燃剂', '泳池与水处理消毒', '钻井液'],
    itemsEn: ['Photographic film and paper', 'Flame retardants', 'Pool and water treatment', 'Drilling fluids'],
  },
  i2: {
    zh: '碘酒和碘伏是最常见的伤口消毒剂；食盐加碘则解决了大范围的甲状腺肿和儿童发育问题。',
    en: 'Tincture of iodine and povidone-iodine are the most familiar wound antiseptics; iodised salt solved widespread goitre and developmental problems.',
    itemsZh: ['碘酒与碘伏消毒', '食盐加碘', '淀粉检验（遇碘变蓝）', '碘钨灯与造影剂'],
    itemsEn: ['Iodine antiseptics', 'Iodised salt', 'The starch-iodine test', 'Halogen lamps and contrast agents'],
  },
  p4: {
    zh: '接触空气就会自燃，必须存放在水下。主要用来制磷酸和磷肥，军事上则作燃烧弹和烟幕弹。',
    en: 'It ignites on contact with air and must be stored under water. Mostly converted to phosphoric acid and fertiliser; militarily used in incendiaries and smoke.',
    itemsZh: ['制磷酸与磷肥', '燃烧弹与烟幕弹', '早期火柴（因中毒已禁用）'],
    itemsEn: ['Phosphoric acid and fertiliser', 'Incendiary and smoke munitions', 'Early matches (banned for poisoning)'],
  },
  s8: {
    zh: '轮胎之所以又弹又耐磨，是因为硫在橡胶分子间架起了交联桥 —— 这就是硫化。',
    en: 'Tyres are springy and hard-wearing because sulfur bridges the rubber chains together — that is vulcanisation.',
    itemsZh: ['橡胶硫化（轮胎）', '制硫酸', '葡萄园与果园杀菌剂', '黑火药与烟花'],
    itemsEn: ['Vulcanising rubber tyres', 'Sulfuric acid production', 'Vineyard fungicides', 'Gunpowder and fireworks'],
  },
  c60: {
    zh: '1985 年发现，1996 年即获诺贝尔化学奖。实际应用仍以研究为主：有机太阳能电池、润滑材料和药物载体。',
    en: 'Discovered in 1985 and awarded the Nobel Prize in 1996. Practical use is still mostly research: organic solar cells, lubricants and drug carriers.',
    itemsZh: ['有机太阳能电池受体材料', '润滑与耐磨添加剂研究', '药物递送载体研究'],
    itemsEn: ['Acceptor material in organic solar cells', 'Lubricant additive research', 'Drug-delivery research'],
  },

  // ---- 无机物 ----
  h2o: {
    zh: '能溶解的物质比任何其他液体都多，所以细胞里的化学反应、洗衣服和工业冷却都靠它。',
    en: 'It dissolves more substances than any other liquid, which is why cell chemistry, laundry and industrial cooling all rely on it.',
    itemsZh: ['饮用与生命活动', '溶剂与清洁', '发电厂与工业冷却', '农业灌溉'],
    itemsEn: ['Drinking and life itself', 'Solvent and cleaning', 'Power-plant and industrial cooling', 'Irrigation'],
  },
  h2o2: {
    zh: '分解后只剩水和氧气，不留残留，因此适合伤口消毒和食品级漂白；高浓度则可作火箭推进剂。',
    en: 'It breaks down into just water and oxygen with no residue, so it suits wound antisepsis and food-grade bleaching; concentrated, it is a rocket propellant.',
    itemsZh: ['双氧水伤口消毒', '头发漂白与牙齿美白', '纸浆与织物漂白', '火箭单组元推进剂'],
    itemsEn: ['Wound antiseptic', 'Hair and tooth bleaching', 'Pulp and textile bleaching', 'Monopropellant rockets'],
  },
  h2s: {
    zh: '沼气、下水道和温泉的臭鸡蛋味就是它。剧毒且高浓度下会麻痹嗅觉，是常见的工业事故气体。',
    en: 'The rotten-egg smell of biogas, sewers and hot springs. Highly toxic, and at high concentration it deadens the sense of smell — a frequent industrial hazard.',
    itemsZh: ['下水道与沼气的臭味来源', '工业有毒气体监测对象', '天然气脱硫的硫来源'],
    itemsEn: ['The smell in sewers and biogas', 'A monitored industrial hazard', 'Source of sulfur from sour gas'],
  },
  co: {
    zh: '无色无味却剧毒，与血红蛋白结合力约为氧气的 200 倍 —— 冬季燃气热水器和炭火中毒的元凶。',
    en: 'Colourless, odourless and deadly: it binds haemoglobin about 200 times more tightly than oxygen, the cause of winter heater and charcoal poisonings.',
    itemsZh: ['一氧化碳报警器的监测对象', '炼铁高炉还原剂', '合成气与化工原料'],
    itemsEn: ['What CO alarms detect', 'Reducing agent in blast furnaces', 'Syngas and chemical feedstock'],
  },
  co2: {
    zh: '汽水的气泡、干冰的白雾、灭火器的喷射都是它；同时也是植物光合作用的原料和头号温室气体。',
    en: 'The fizz in soda, the fog from dry ice and the blast from an extinguisher — and also the raw material of photosynthesis and the leading greenhouse gas.',
    itemsZh: ['碳酸饮料气泡', '干冰冷藏与舞台烟雾', '二氧化碳灭火器', '温室气肥与光合作用'],
    itemsEn: ['Fizzy drinks', 'Dry ice for cooling and stage fog', 'CO2 fire extinguishers', 'Photosynthesis and greenhouse enrichment'],
  },
  so2: {
    zh: '葡萄酒瓶上的"含亚硫酸盐"就来自它 —— 能抑菌抗氧化；但排入大气会形成酸雨。',
    en: 'The "contains sulfites" on a wine label traces back to it: an antimicrobial and antioxidant. Released into the air, though, it makes acid rain.',
    itemsZh: ['葡萄酒与干果防腐', '纸浆与织物漂白', '制硫酸的中间体', '酸雨的主要成因'],
    itemsEn: ['Wine and dried-fruit preservation', 'Pulp and textile bleaching', 'Intermediate in sulfuric acid', 'Main cause of acid rain'],
  },
  nh3: {
    zh: '哈伯法合成氨把空气中的氮变成化肥，被认为是养活了地球上约一半人口的化学反应。',
    en: 'The Haber process turns air into fertiliser; it is often credited with feeding roughly half the people alive.',
    itemsZh: ['氮肥（尿素、硝铵）', '工业与冷库制冷剂', '含氨玻璃清洁剂', '柴油车尾气脱硝'],
    itemsEn: ['Nitrogen fertiliser', 'Industrial refrigeration', 'Ammonia glass cleaner', 'Diesel exhaust NOx treatment'],
  },
  hcl: {
    zh: '胃里就有它，负责消化蛋白质和杀灭细菌；家里的除垢剂、洁厕灵也主要靠盐酸。',
    en: 'Your stomach makes it to digest protein and kill bacteria; household descalers and toilet cleaners are mostly hydrochloric acid.',
    itemsZh: ['胃酸（消化与杀菌）', '除垢剂与洁厕灵', '钢材酸洗除锈', '食品与药物生产'],
    itemsEn: ['Stomach acid', 'Descalers and toilet cleaners', 'Steel pickling', 'Food and drug manufacture'],
  },
  hf: {
    zh: '唯一能腐蚀玻璃的常见酸，用于玻璃蚀刻和芯片清洗；但会穿透皮肤直接侵蚀骨骼，极其危险。',
    en: 'The one common acid that attacks glass, used for etching and wafer cleaning — but it penetrates skin and attacks bone, making it extremely dangerous.',
    itemsZh: ['玻璃蚀刻与磨砂', '半导体晶圆清洗', '含氟化合物原料', '铝电解助熔剂'],
    itemsEn: ['Glass etching and frosting', 'Semiconductor wafer cleaning', 'Fluorochemical feedstock', 'Aluminium smelting flux'],
  },
  hcn: {
    zh: '极少量即可致命，是历史上臭名昭著的毒物；工业上却是电镀金银和制造有机玻璃的必需原料。',
    en: 'Lethal in tiny amounts and infamous as a poison, yet industrially essential for gold and silver plating and for making acrylic glass.',
    itemsZh: ['金银电镀与提金', '有机玻璃与尼龙原料', '苦杏仁与木薯中的天然来源'],
    itemsEn: ['Gold and silver plating', 'Feedstock for acrylic and nylon', 'Naturally present in bitter almonds and cassava'],
  },
  no: {
    zh: '人体自身合成它来舒张血管 —— 硝酸甘油治心绞痛和伟哥的作用机理都与之相关，相关研究获 1998 年诺贝尔奖。',
    en: 'The body makes it to relax blood vessels: nitroglycerin for angina and Viagra both work through this pathway, research that won the 1998 Nobel Prize.',
    itemsZh: ['体内血管舒张信号分子', '新生儿肺动脉高压吸入治疗', '汽车尾气与空气污染物'],
    itemsEn: ['Signalling molecule that dilates vessels', 'Inhaled therapy for newborn lung hypertension', 'Vehicle exhaust pollutant'],
  },
  no2: {
    zh: '城市空气质量指标里的"二氧化氮"就是它，主要来自机动车尾气，是光化学烟雾和酸雨的推手。',
    en: 'The NO2 on urban air-quality dashboards, mostly from vehicle exhaust, and a driver of photochemical smog and acid rain.',
    itemsZh: ['空气质量监测指标', '光化学烟雾成因', '制硝酸的中间体'],
    itemsEn: ['Tracked air-quality pollutant', 'Cause of photochemical smog', 'Intermediate in nitric acid production'],
  },
  n2o: {
    zh: '俗称笑气。牙科和分娩镇痛仍在使用，食品上则用作奶油发泡剂 —— 但滥用吸食会造成不可逆的神经损伤。',
    en: 'Laughing gas: still used in dentistry and childbirth analgesia, and as the propellant in whipped cream — but recreational abuse causes irreversible nerve damage.',
    itemsZh: ['牙科与产科镇痛', '奶油发泡剂', '赛车发动机增氧', '强效温室气体'],
    itemsEn: ['Dental and obstetric analgesia', 'Whipped-cream propellant', 'Engine power boosting', 'Potent greenhouse gas'],
  },
  so3: {
    zh: '本身很少直接使用，但它是接触法制硫酸的关键一步 —— 全球每年数亿吨硫酸都要经过它。',
    en: 'Rarely used directly, but it is the pivotal step of the contact process: every one of the hundreds of millions of tonnes of sulfuric acid passes through it.',
    itemsZh: ['制硫酸的关键中间体', '洗涤剂磺化原料', '酸雨形成的中间产物'],
    itemsEn: ['Key intermediate in sulfuric acid', 'Sulfonation for detergents', 'Intermediate in acid-rain formation'],
  },
  bf3: {
    zh: '典型的路易斯酸，极易夺取电子对，因此是有机合成和聚合反应中最常用的催化剂之一。',
    en: 'A textbook Lewis acid that eagerly grabs electron pairs, making it one of the most-used catalysts in organic synthesis and polymerisation.',
    itemsZh: ['有机合成催化剂', '聚合反应引发剂', '中子探测器填充气'],
    itemsEn: ['Organic synthesis catalyst', 'Polymerisation initiator', 'Neutron-detector fill gas'],
  },
  ph3: {
    zh: '磷化铝熏蒸剂遇水放出膦气，是粮仓杀虫的主要手段；剧毒，也用于半导体掺杂。',
    en: 'Aluminium phosphide fumigant releases phosphine on contact with moisture, the mainstay of grain-store pest control; highly toxic, it also dopes semiconductors.',
    itemsZh: ['粮仓熏蒸杀虫', '半导体 n 型掺杂', '沼泽"鬼火"的成因之一'],
    itemsEn: ['Grain fumigation', 'n-type semiconductor doping', 'A cause of marsh will-o’-the-wisps'],
  },
  sf6: {
    zh: '绝缘性能远超空气，高压开关柜里灌的就是它 —— 但它是已知最强的温室气体，单分子效应约为二氧化碳的两万倍。',
    en: 'A far better insulator than air, which is why high-voltage switchgear is filled with it — yet it is the most potent greenhouse gas known, about 20 000 times CO2 per molecule.',
    itemsZh: ['高压电气开关绝缘', '镁合金铸造保护气', '医学超声造影微泡', '最强温室气体之一'],
    itemsEn: ['High-voltage switchgear insulation', 'Magnesium casting cover gas', 'Ultrasound contrast microbubbles', 'Extremely potent greenhouse gas'],
  },
  pcl5: {
    zh: '有机合成中最常用的氯化试剂之一，能把羟基一步换成氯原子，是制药和农药合成的常规工具。',
    en: 'One of the most common chlorinating reagents in organic synthesis, swapping a hydroxyl for chlorine in a single step — routine in pharmaceutical and agrochemical work.',
    itemsZh: ['有机合成氯化试剂', '制药中间体生产', '锂电池电解质原料'],
    itemsEn: ['Chlorinating reagent', 'Pharmaceutical intermediates', 'Precursor for battery electrolytes'],
  },
  xef4: {
    zh: '1962 年前，教科书还断言稀有气体不能形成化合物。氙化合物的合成直接改写了化学的基本认知。',
    en: 'Before 1962 textbooks insisted noble gases could not form compounds. Making xenon compounds rewrote a basic assumption of chemistry.',
    itemsZh: ['改写稀有气体化学的实验', '强氧化剂与氟化试剂', '化学教学的经典案例'],
    itemsEn: ['The experiment that rewrote noble-gas chemistry', 'Strong oxidiser and fluorinating agent', 'A teaching classic'],
  },
  h2so4: {
    zh: '产量常被用来衡量一个国家的工业规模。汽车电瓶里的电解液就是稀硫酸，管道疏通剂也多以浓硫酸为主。',
    en: 'Its output is a classic measure of a country’s industrial scale. The electrolyte in a car battery is dilute sulfuric acid, and drain openers are often concentrated acid.',
    itemsZh: ['汽车铅酸电池电解液', '磷肥生产', '管道疏通剂', '钢材酸洗与化工原料'],
    itemsEn: ['Car battery electrolyte', 'Phosphate fertiliser production', 'Drain openers', 'Steel pickling and chemicals'],
  },
  hno3: {
    zh: '硝酸铵化肥和几乎所有传统炸药（TNT、硝化甘油）都由它制得；与盐酸混合成王水，可溶解黄金。',
    en: 'It makes ammonium nitrate fertiliser and virtually every classical explosive (TNT, nitroglycerin); mixed with hydrochloric acid it becomes aqua regia, which dissolves gold.',
    itemsZh: ['硝酸铵化肥', '炸药与火箭推进剂', '王水（溶解金铂）', '金属蚀刻与电子清洗'],
    itemsEn: ['Ammonium nitrate fertiliser', 'Explosives and rocket propellants', 'Aqua regia', 'Metal etching'],
  },

  // ---- 有机物 ----
  ch4: {
    zh: '天然气的主要成分，家里的燃气灶和热水器烧的就是它；也是仅次于二氧化碳的温室气体。',
    en: 'The main component of natural gas that burns in your hob and water heater, and the second most important greenhouse gas after CO2.',
    itemsZh: ['家用天然气与燃气灶', '燃气发电与供暖', '制氢与合成氨原料', '沼气与温室气体'],
    itemsEn: ['Domestic gas cooking', 'Gas power and heating', 'Feedstock for hydrogen and ammonia', 'Biogas and greenhouse gas'],
  },
  ch2o: {
    zh: '福尔马林（甲醛水溶液）用于保存标本；但人造板和家具胶粘剂释放的甲醛是最受关注的室内污染物。',
    en: 'Formalin preserves biological specimens, but the formaldehyde released by engineered wood and furniture adhesives is the most-watched indoor pollutant.',
    itemsZh: ['福尔马林标本保存', '人造板与家具胶粘剂', '室内空气污染检测对象', '消毒与疫苗灭活'],
    itemsEn: ['Formalin specimen preservation', 'Adhesives in engineered wood', 'A key indoor-air pollutant', 'Disinfection and vaccine inactivation'],
  },
  c2h2: {
    zh: '氧炔焰能达到约 3300 ℃，是少数能熔断厚钢板的火焰；也用作水果的人工催熟剂。',
    en: 'An oxyacetylene flame reaches about 3300 °C, one of the few hot enough to cut thick steel; it is also used to ripen fruit artificially.',
    itemsZh: ['氧炔焊接与金属切割', '水果人工催熟', '合成橡胶与塑料原料'],
    itemsEn: ['Oxyacetylene welding and cutting', 'Artificial fruit ripening', 'Feedstock for rubber and plastics'],
  },
  c2h4: {
    zh: '产量最大的有机化工产品，聚乙烯（塑料袋、保鲜膜）就由它聚合而成；同时也是植物自身的催熟激素。',
    en: 'The most-produced organic chemical: polyethylene (carrier bags, cling film) is polymerised from it — and it is also the plant hormone that ripens fruit.',
    itemsZh: ['聚乙烯塑料袋与保鲜膜', '香蕉等水果催熟', '防冻液与化工原料', '合成纤维'],
    itemsEn: ['Polyethylene bags and cling film', 'Ripening bananas and other fruit', 'Antifreeze and chemical feedstock', 'Synthetic fibres'],
  },
  ch3oh: {
    zh: '外观和气味都像乙醇，却会代谢成甲酸导致失明甚至死亡 —— 假酒中毒的元凶正是它。',
    en: 'It looks and smells like ethanol but metabolises into formic acid, causing blindness or death — the culprit behind bootleg-liquor poisonings.',
    itemsZh: ['甲醇燃料与生物柴油', '玻璃水与防冻液', '甲醛与塑料原料', '假酒中毒的元凶'],
    itemsEn: ['Methanol fuel and biodiesel', 'Windscreen washer and antifreeze', 'Feedstock for formaldehyde', 'Cause of bootleg-alcohol poisoning'],
  },
  c2h5oh: {
    zh: '75% 浓度杀菌效果最好 —— 太浓会让细菌表面蛋白迅速凝固，反而挡住酒精继续渗入。',
    en: 'It disinfects best at 75%: any stronger and it coagulates surface proteins so fast that the seal blocks further penetration.',
    itemsZh: ['医用消毒酒精与免洗洗手液', '酒精饮料', '燃料乙醇（乙醇汽油）', '香精与药物溶剂'],
    itemsEn: ['Medical alcohol and hand sanitiser', 'Alcoholic drinks', 'Fuel ethanol', 'Solvent for flavours and drugs'],
  },
  c6h6: {
    zh: '塑料、合成纤维、染料和药物的基础原料之一，但已确认为致癌物，工业接触受严格管控。',
    en: 'A base feedstock for plastics, synthetic fibres, dyes and drugs — but a confirmed carcinogen, so industrial exposure is tightly controlled.',
    itemsZh: ['塑料与合成纤维原料', '染料与药物中间体', '汽油组分', '确认致癌物，接触受管控'],
    itemsEn: ['Feedstock for plastics and fibres', 'Dye and drug intermediates', 'Petrol component', 'A regulated carcinogen'],
  },
  c2h6: {
    zh: '天然气中含量第二的成分。工业上主要被裂解成乙烯 —— 也就是变成塑料的第一步。',
    en: 'The second most abundant component of natural gas. Industrially it is cracked into ethylene, the first step towards plastic.',
    itemsZh: ['裂解制乙烯（塑料原料）', '天然气组分与燃料', '制冷剂'],
    itemsEn: ['Cracked to ethylene for plastics', 'Natural gas component and fuel', 'Refrigerant'],
  },
  c3h8: {
    zh: '液化石油气（LPG）的主要成分，加压即可液化装罐，是野外烧烤炉、热气球和无管道地区的主要燃料。',
    en: 'The main component of LPG: it liquefies under modest pressure, fuelling camping stoves, hot-air balloons and homes off the gas grid.',
    itemsZh: ['液化石油气罐（煤气罐）', '户外烧烤炉与热气球', '打火机燃料', '乡村供暖与炊事'],
    itemsEn: ['LPG cylinders', 'Camping stoves and balloons', 'Lighter fuel', 'Off-grid heating and cooking'],
  },
  ch3cl: {
    zh: '有机硅工业的起点 —— 硅橡胶、硅油和防水密封胶都从它开始合成；曾作制冷剂，因毒性淘汰。',
    en: 'The starting point of the silicone industry — silicone rubber, oils and waterproof sealants all begin here; once a refrigerant, dropped for toxicity.',
    itemsZh: ['硅橡胶与硅油生产起点', '防水密封胶原料', '早期制冷剂（已淘汰）'],
    itemsEn: ['Start of silicone manufacture', 'Feedstock for sealants', 'Early refrigerant (obsolete)'],
  },
  chcl3: {
    zh: '19 世纪最重要的吸入麻醉剂，但因肝毒性和心律失常风险早已被淘汰；如今主要作实验室溶剂和制冷剂原料。',
    en: 'The leading inhaled anaesthetic of the 19th century, long abandoned for liver toxicity and cardiac risk; today mainly a lab solvent and refrigerant precursor.',
    itemsZh: ['实验室萃取溶剂', '特氟龙制冷剂原料', '历史上的吸入麻醉剂'],
    itemsEn: ['Laboratory extraction solvent', 'Precursor for PTFE refrigerants', 'Historic anaesthetic'],
  },
  ccl4: {
    zh: '曾是最常见的灭火剂和干洗溶剂，后来发现它既伤肝又破坏臭氧层，已被《蒙特利尔议定书》全面禁用。',
    en: 'Once the most common fire extinguisher and dry-cleaning solvent, until it proved both hepatotoxic and ozone-depleting; now banned under the Montreal Protocol.',
    itemsZh: ['曾用作灭火剂与干洗剂（已禁用）', '曾用于制冷剂生产', '化学教学的经典非极性分子'],
    itemsEn: ['Former extinguisher and dry-cleaning solvent (banned)', 'Former refrigerant feedstock', 'A teaching classic for non-polar molecules'],
  },
  ch3cho: {
    zh: '酒精在肝脏代谢的第一步产物。亚洲人中约四成乙醛脱氢酶活性偏低，喝酒脸红正是乙醛堆积所致。',
    en: 'The first product of alcohol metabolism. Roughly 40% of East Asians have a low-activity variant of the enzyme that clears it, which is why drinking makes them flush.',
    itemsZh: ['酒精代谢中间产物（脸红与宿醉）', '香精与香料合成', '树脂与塑料原料'],
    itemsEn: ['Alcohol metabolite behind flushing and hangovers', 'Flavour and fragrance synthesis', 'Resin and plastics feedstock'],
  },
  acetone: {
    zh: '洗甲水的主要成分，也是溶解油脂和树脂能力极强的常用溶剂；人体在长时间断食时也会产生它。',
    en: 'The main ingredient of nail-polish remover and a powerful solvent for oils and resins; the body also produces it during prolonged fasting.',
    itemsZh: ['洗甲水', '实验室与工业溶剂', '有机玻璃（亚克力）原料', '糖尿病酮症的代谢产物'],
    itemsEn: ['Nail-polish remover', 'Lab and industrial solvent', 'Feedstock for acrylic glass', 'Metabolite in ketosis'],
  },
  ch3cooh: {
    zh: '食醋中约含 3–5% 的乙酸，酸味就来自它；家用除水垢、清洁玻璃也常用白醋。',
    en: 'Vinegar is 3-5% acetic acid, and that is where the sourness comes from; white vinegar is also a household descaler and glass cleaner.',
    itemsZh: ['食醋与调味', '家用除水垢与清洁', '醋酸纤维与涤纶原料', '食品防腐剂'],
    itemsEn: ['Vinegar and seasoning', 'Household descaling', 'Acetate fibre and polyester feedstock', 'Food preservative'],
  },
  ch3och3: {
    zh: '与乙醇分子式相同却性质迥异，是同分异构的经典范例。作气雾剂推进剂和清洁柴油替代燃料。',
    en: 'Same formula as ethanol yet completely different — the textbook case of structural isomerism. Used as an aerosol propellant and a clean diesel substitute.',
    itemsZh: ['喷雾罐推进剂', '清洁柴油替代燃料', '化学教学的同分异构范例'],
    itemsEn: ['Aerosol propellant', 'Clean diesel substitute', 'Teaching example of isomerism'],
  },
  toluene: {
    zh: '油漆稀释剂和胶水的主要溶剂，也是 TNT 炸药的原料；挥发性强，长期吸入会损伤神经系统。',
    en: 'The main solvent in paint thinners and adhesives, and the raw material for TNT; volatile enough that chronic inhalation damages the nervous system.',
    itemsZh: ['油漆稀释剂与胶水溶剂', 'TNT 炸药原料', '汽油辛烷值提升剂', '指甲油与印刷油墨'],
    itemsEn: ['Paint thinner and adhesive solvent', 'Raw material for TNT', 'Octane booster in petrol', 'Nail polish and printing inks'],
  },
  phenol: {
    zh: '历史上第一种外科消毒剂 —— 李斯特用它把手术死亡率大幅降低；今天则是酚醛树脂和多种药物的原料。',
    en: 'The first surgical antiseptic: Lister used it to cut operative mortality dramatically. Today it is the feedstock for phenolic resins and many drugs.',
    itemsZh: ['最早的外科消毒剂', '酚醛树脂（电木、层压板）', '阿司匹林等药物原料', '喉痛喷雾中的局部麻醉成分'],
    itemsEn: ['The first surgical antiseptic', 'Phenolic resins and laminates', 'Feedstock for aspirin and other drugs', 'Throat-spray anaesthetic'],
  },
  naphthalene: {
    zh: '传统樟脑丸的成分，靠常温升华出的蒸气驱虫；因健康顾虑，许多国家已改用其他防蛀剂。',
    en: 'The active ingredient of old-fashioned mothballs, working through vapour that sublimes at room temperature; health concerns have pushed many countries to alternatives.',
    itemsZh: ['樟脑丸防蛀', '染料与增塑剂原料', '混凝土减水剂', '曾用于家用驱虫'],
    itemsEn: ['Mothballs', 'Dye and plasticiser feedstock', 'Concrete water reducers', 'Former household insect repellent'],
  },
  urea: {
    zh: '用量最大的氮肥。护肤品里的尿素能锁水软化角质；柴油车加的"车用尿素"则用来分解尾气中的氮氧化物。',
    en: 'The world’s leading nitrogen fertiliser. In skincare it holds water and softens keratin; in diesel vehicles, AdBlue urea solution breaks down exhaust NOx.',
    itemsZh: ['尿素氮肥', '护肤品保湿与去角质', '柴油车尾气处理液（车用尿素）', '人体尿液的主要含氮废物'],
    itemsEn: ['Urea fertiliser', 'Moisturising and keratolytic skincare', 'AdBlue diesel exhaust fluid', 'The main nitrogen waste in urine'],
  },
  glycine: {
    zh: '组成蛋白质的 20 种氨基酸中最小的一个，因为侧链只是一个氢原子，能挤进胶原蛋白紧密的三股螺旋里。',
    en: 'The smallest of the 20 protein amino acids: its side chain is a single hydrogen, small enough to fit inside collagen’s tight triple helix.',
    itemsZh: ['蛋白质与胶原蛋白的组成单元', '食品增味剂与缓冲剂', '中枢神经抑制性递质', '生化实验缓冲液'],
    itemsEn: ['Building block of proteins and collagen', 'Food flavour enhancer and buffer', 'Inhibitory neurotransmitter', 'Biochemical buffers'],
  },
  h3po4: {
    zh: '可乐那股独特的涩酸味就来自磷酸；工业上主要用于制磷肥，也用于钢铁除锈和牙科蚀刻。',
    en: 'The sharp tang of cola comes from phosphoric acid; industrially it makes phosphate fertiliser and also derusts steel and etches teeth.',
    itemsZh: ['可乐等碳酸饮料酸味剂', '磷肥生产', '钢铁除锈与磷化', '牙科釉质蚀刻'],
    itemsEn: ['Acidulant in cola', 'Phosphate fertiliser', 'Rust removal and phosphating', 'Dental etching'],
  },
  n2h4: {
    zh: '高能量密度且能长期常温储存，是卫星和探测器最常用的姿态控制推进剂；工业上也用作锅炉除氧剂。',
    en: 'Energy-dense and storable at room temperature, it is the standard thruster propellant for satellites and probes; industrially it scavenges oxygen from boiler water.',
    itemsZh: ['卫星与探测器姿控推进剂', '锅炉水除氧剂', '发泡剂与农药原料'],
    itemsEn: ['Satellite and probe thrusters', 'Boiler-water oxygen scavenger', 'Blowing agents and agrochemicals'],
  },
  h2co3: {
    zh: '汽水、啤酒和气泡水里的「气」，本质上是溶解的二氧化碳与它之间的平衡；血液也靠这套平衡稳定 pH。',
    en: 'The fizz in soda, beer and sparkling water is really the balance between dissolved CO2 and this acid; blood uses the same equilibrium to hold its pH steady.',
    itemsZh: ['碳酸饮料的酸味与气泡', '血液的酸碱缓冲系统', '溶洞与钟乳石的形成', '海洋酸化'],
    itemsEn: ['Fizz and tang in soft drinks', 'The blood bicarbonate buffer', 'Cave and stalactite formation', 'Ocean acidification'],
  },
  hclo: {
    zh: '84 消毒液、漂白水和泳池氯片起作用时，真正杀菌的都是它；人体的中性粒细胞也会合成它来杀灭病原体。',
    en: 'Whatever the label says, bleach, pool chlorine or disinfectant, this is the species that actually kills microbes. Your own neutrophils make it too.',
    itemsZh: ['漂白水与消毒液的有效成分', '泳池与自来水消毒', '次氯酸消毒喷雾', '人体免疫细胞的杀菌武器'],
    itemsEn: ['Active agent in bleach and disinfectant', 'Pool and tap-water treatment', 'Hypochlorous acid sprays', 'A weapon of human immune cells'],
  },
  sih4: {
    zh: '芯片、液晶面板和太阳能电池上的硅薄膜，几乎都是让硅烷在高温下分解沉积出来的。',
    en: 'The silicon films on chips, LCD panels and solar cells are nearly all deposited by decomposing silane at high temperature.',
    itemsZh: ['芯片硅薄膜气相沉积', '太阳能电池制造', '液晶面板镀膜'],
    itemsEn: ['Silicon film deposition for chips', 'Solar-cell manufacture', 'LCD panel coating'],
  },
  hcooh: {
    zh: '蚂蚁、蜜蜂和荨麻靠它防御。工业上用于皮革鞣制、橡胶凝固和青贮饲料防腐。',
    en: 'The defence chemical of ants, bees and nettles. Industrially it tans leather, coagulates rubber latex and preserves silage.',
    itemsZh: ['蚂蚁与蜂类的防御物质', '皮革鞣制', '橡胶乳凝固', '青贮饲料防腐'],
    itemsEn: ['Ant and bee defence', 'Leather tanning', 'Coagulating rubber latex', 'Silage preservation'],
  },
  ethyleneglycol: {
    zh: '汽车防冻液的主成分，也是 PET 塑料瓶和涤纶纤维的两大原料之一。有甜味，宠物误食极易致命。',
    en: 'The main ingredient of engine antifreeze and one of the two feedstocks for PET bottles and polyester fibre. It tastes sweet, which makes it deadly to pets.',
    itemsZh: ['汽车防冻液与冷却液', 'PET 塑料瓶原料', '涤纶（聚酯）纤维', '飞机除冰液'],
    itemsEn: ['Engine antifreeze', 'PET bottle feedstock', 'Polyester fibre', 'Aircraft de-icing fluid'],
  },
  glycerol: {
    zh: '护肤品成分表上几乎必有的保湿剂；也是所有油脂的骨架 —— 制皂时把油脂水解，剩下的就是甘油。',
    en: 'The humectant on almost every skincare label, and the backbone of all fats: hydrolysing oil to make soap leaves glycerol behind.',
    itemsZh: ['护肤品与化妆品保湿剂', '牙膏与药品甜味剂', '甘油三酯（油脂）骨架', '硝化甘油炸药原料'],
    itemsEn: ['Skincare humectant', 'Sweetener in toothpaste and medicines', 'Backbone of all fats', 'Feedstock for nitroglycerin'],
  },
  diethylether: {
    zh: '1846 年乙醚麻醉的公开演示是外科史的分水岭；今天主要作萃取溶剂和柴油发动机冷启动助剂。',
    en: 'The 1846 public demonstration of ether anaesthesia was a turning point in surgery; today it is mainly an extraction solvent and a diesel cold-start aid.',
    itemsZh: ['实验室萃取溶剂', '柴油机冷启动喷雾', '历史上的外科麻醉剂'],
    itemsEn: ['Laboratory extraction solvent', 'Diesel starting fluid', 'Historic surgical anaesthetic'],
  },
  ethylacetate: {
    zh: '洗甲水、白乳胶和指甲油那股果香就是它。毒性低、挥发快，还用于咖啡豆脱咖啡因。',
    en: 'The fruity smell of nail-polish remover, white glue and nail varnish. Low in toxicity and fast to evaporate, it is also used to decaffeinate coffee.',
    itemsZh: ['洗甲水与指甲油', '胶水与油墨溶剂', '咖啡豆脱咖啡因', '水果香精成分'],
    itemsEn: ['Nail-polish remover', 'Solvent in glues and inks', 'Decaffeinating coffee', 'Fruit flavourings'],
  },
  lacticacid: {
    zh: '酸奶、泡菜和酸面包的酸味都来自乳酸菌发酵；护肤上作果酸换肤，医用可降解缝线也由它聚合而成。',
    en: 'Lactic-acid bacteria give yoghurt, pickles and sourdough their tang; in skincare it is an AHA exfoliant, and polymerised it becomes dissolvable surgical sutures.',
    itemsZh: ['酸奶与泡菜发酵', '果酸（AHA）护肤品', '可降解手术缝线与 PLA 塑料', '食品防腐与调味'],
    itemsEn: ['Yoghurt and pickle fermentation', 'AHA skincare', 'Dissolvable sutures and PLA plastic', 'Food preservation'],
  },
  alanine: {
    zh: '构成蛋白质的 20 种氨基酸之一，肌肉中含量很高。运动时肌肉靠它把氮运回肝脏再合成葡萄糖。',
    en: 'One of the 20 protein amino acids and abundant in muscle, which uses it to shuttle nitrogen back to the liver to be remade into glucose.',
    itemsZh: ['蛋白质组成单元', '肌肉与肝脏间的葡萄糖-丙氨酸循环', '食品增味与营养补充剂'],
    itemsEn: ['Protein building block', 'The glucose-alanine cycle', 'Food flavouring and supplements'],
  },
  vinylchloride: {
    zh: '全球第三大塑料 PVC 的单体。水管、电线绝缘层、地板革、人造革和输液袋都由它聚合而来。',
    en: 'The monomer of PVC, the third-largest plastic in the world: water pipes, cable insulation, vinyl flooring, synthetic leather and IV bags all come from it.',
    itemsZh: ['PVC 水管与排水管', '电线电缆绝缘层', '地板革与人造革', '医用输液袋'],
    itemsEn: ['PVC pipes', 'Cable insulation', 'Vinyl flooring and leatherette', 'Medical IV bags'],
  },
  propene: {
    zh: '聚丙烯的单体。保鲜盒能进微波炉、编织袋耐撕、口罩熔喷布能滤住颗粒，靠的都是聚丙烯。',
    en: 'The monomer of polypropylene: microwave-safe containers, tear-resistant woven sacks and the meltblown filter layer in face masks are all PP.',
    itemsZh: ['聚丙烯保鲜盒与餐具', '编织袋与打包带', '口罩熔喷过滤层', '汽车保险杠与内饰'],
    itemsEn: ['Polypropylene containers', 'Woven sacks and strapping', 'Mask filter layers', 'Car bumpers and trim'],
  },
  tetrafluoroethylene: {
    zh: '聚合后就是特氟龙。不粘锅、防水透气面料、水管生料带和化工耐腐蚀衬里都是它的产物。',
    en: 'Polymerised it becomes PTFE: non-stick pans, breathable waterproof fabrics, plumbers thread tape and corrosion-proof chemical linings.',
    itemsZh: ['不粘锅涂层', '防水透气面料', '水管生料带', '化工耐腐蚀衬里与轴承'],
    itemsEn: ['Non-stick pan coatings', 'Breathable waterproof fabrics', 'PTFE thread tape', 'Chemical-resistant linings'],
  },
  styrene: {
    zh: '聚苯乙烯的单体。发泡后是外卖盒和快递泡沫，透明硬质的是一次性餐具；ABS 塑料（乐高积木）也含它。',
    en: 'The monomer of polystyrene: foamed into takeaway boxes and packing foam, clear and rigid for disposable cutlery, and a component of ABS, the plastic of Lego bricks.',
    itemsZh: ['泡沫塑料餐盒与快递填充', '一次性透明餐具与 CD 盒', 'ABS 塑料（乐高、家电外壳）', '合成橡胶轮胎'],
    itemsEn: ['Foam boxes and packing', 'Clear disposable cutlery', 'ABS plastic (Lego, appliances)', 'Synthetic rubber tyres'],
  },
  cfc12: {
    zh: '曾是冰箱和空调的标准制冷剂，也用作喷雾推进剂。1987 年《蒙特利尔议定书》后全球停产 —— 这是人类第一次成功修复全球性环境损害。',
    en: 'Once the standard refrigerant in fridges and air conditioners and a common aerosol propellant. Phased out worldwide after the 1987 Montreal Protocol, humanity first successful repair of global environmental damage.',
    itemsZh: ['曾用于冰箱空调制冷（已禁）', '曾作喷雾罐推进剂（已禁）', '臭氧空洞的主要成因', '《蒙特利尔议定书》的管控对象'],
    itemsEn: ['Former fridge and AC refrigerant (banned)', 'Former aerosol propellant (banned)', 'Main cause of the ozone hole', 'Regulated by the Montreal Protocol'],
  },
  adenine: {
    zh: 'DNA 与 RNA 的四种碱基之一，在双螺旋中固定与胸腺嘧啶配对；也是 ATP、NAD 和辅酶 A 的组成部分。',
    en: 'One of the four bases of DNA and RNA, always pairing with thymine in the double helix; it is also part of ATP, NAD and coenzyme A.',
    itemsZh: ['DNA 与 RNA 的碱基 A', 'ATP（细胞能量货币）的组成', '辅酶 NAD 的组成', '基因测序与检测'],
    itemsEn: ['The base A in DNA and RNA', 'Part of ATP, the cell energy currency', 'The coenzyme NAD', 'Genetic sequencing'],
  },
  caffeine: {
    zh: '世界上使用最广的精神活性物质。咖啡、茶、可乐和能量饮料都靠它提神；也常加进感冒药和止痛药增强药效。',
    en: 'The most widely used psychoactive substance in the world, behind coffee, tea, cola and energy drinks; it is also added to cold and pain medicines to boost their effect.',
    itemsZh: ['咖啡、茶与可乐', '能量饮料', '感冒药与复方止痛药', '早产儿呼吸暂停治疗'],
    itemsEn: ['Coffee, tea and cola', 'Energy drinks', 'Cold and pain medicines', 'Treating apnoea in premature infants'],
  },
  aspirin: {
    zh: '解热镇痛消炎，还能抑制血小板凝集 —— 心梗和中风高危人群长期服用的小剂量阿司匹林正是靠这一点。',
    en: 'It reduces fever, pain and inflammation, and blocks platelet aggregation, which is why people at risk of heart attack or stroke take a small daily dose.',
    itemsZh: ['解热镇痛与消炎', '小剂量抗血栓（心梗、中风预防）', '风湿与关节炎治疗', '家庭常备药'],
    itemsEn: ['Fever, pain and inflammation', 'Low-dose blood thinning', 'Rheumatic and arthritic conditions', 'A household staple'],
  },
  paracetamol: {
    zh: '最常用的退烧止痛药。不刺激胃、儿童孕妇相对安全，但过量直接损伤肝脏，且许多复方感冒药都含它，容易叠加超量。',
    en: 'The most-used fever and pain remedy: gentle on the stomach and relatively safe in pregnancy and childhood, but an overdose damages the liver, and many combination cold remedies contain it so doses stack up easily.',
    itemsZh: ['退烧与止痛', '儿童与孕妇常用退烧药', '复方感冒药成分', '过量致肝损伤（注意叠加）'],
    itemsEn: ['Fever and pain relief', 'Common paediatric antipyretic', 'Ingredient in combination cold remedies', 'Liver damage on overdose'],
  },
  glucose: {
    zh: '血糖就是它。大脑几乎只烧葡萄糖，每天约消耗 120 克；也是淀粉、纤维素和糖原的基本单元。',
    en: 'This is blood sugar. The brain runs almost exclusively on glucose, burning about 120 g a day, and it is the repeating unit of starch, cellulose and glycogen.',
    itemsZh: ['血糖与细胞供能', '葡萄糖注射液与口服补液盐', '淀粉、纤维素、糖原的单元', '糖尿病监测的核心指标'],
    itemsEn: ['Blood sugar and cellular fuel', 'Glucose drips and oral rehydration', 'The unit of starch and cellulose', 'The core diabetes measure'],
  },

  // ---- 生活中的其他分子 ----
  h3bo3: {
    zh: '弱酸而温和，杀虫效果却很确定：厨房里对付蟑螂和蚂蚁的硼酸饵剂就是它。也用于眼部冲洗液和玻璃、陶釉配方。',
    en: 'A weak, mild acid that is nevertheless a reliable insecticide — the boric-acid bait used against cockroaches and ants. It also goes into eyewash and into glass and ceramic glazes.',
    itemsZh: ['蟑螂与蚂蚁饵剂', '眼部冲洗与消毒', '耐热玻璃与陶釉', '木材防腐阻燃'],
    itemsEn: ['Cockroach and ant bait', 'Eyewash and antiseptics', 'Borosilicate glass and glazes', 'Wood preservative and flame retardant'],
  },
  c4h10: {
    zh: '打火机和便携卡式炉里的燃料。它在常温下稍加压就变成液体，体积缩小几百倍，所以一只小小的打火机能烧很久。',
    en: 'The fuel in lighters and portable gas stoves. A little pressure liquefies it at room temperature, shrinking it hundreds of times over, which is why a small lighter lasts so long.',
    itemsZh: ['打火机燃料', '卡式炉与野营炉气罐', '液化石油气（与丙烷混合）', '喷雾罐的抛射剂'],
    itemsEn: ['Lighter fuel', 'Camping stove canisters', 'LPG, blended with propane', 'Aerosol propellant'],
  },
  cyclohexane: {
    zh: '主要用来造尼龙 —— 你身上的冲锋衣、背包带、伞面很可能都从它开始。实验室里也是常用的非极性溶剂。',
    en: 'Mostly made into nylon, so the shell jacket, rucksack strap and umbrella you own probably started here. It is also a workhorse non-polar solvent.',
    itemsZh: ['制造尼龙 6 与尼龙 66', '油脂、树脂的溶剂', '橡胶与涂料工业', '教科书里的椅式构象范例'],
    itemsEn: ['Making nylon 6 and 66', 'Solvent for oils and resins', 'Rubber and coatings', 'The textbook chair conformation'],
  },
  isopropanol: {
    zh: '医用酒精棉片、免洗洗手液和电子产品清洁剂的主力。挥发快、不留痕，擦拭屏幕和电路板比水安全。',
    en: 'The workhorse of alcohol wipes, hand sanitiser and electronics cleaner: it flashes off fast and leaves no residue, which makes it safer than water on screens and circuit boards.',
    itemsZh: ['酒精棉片与免洗洗手液', '屏幕与电路板清洁', '玻璃水与防冻剂', '化妆品与香水溶剂'],
    itemsEn: ['Alcohol wipes and sanitiser', 'Cleaning screens and boards', 'Screenwash and de-icer', 'Cosmetics solvent'],
  },
  propyleneglycol: {
    zh: '食品级保湿剂，在蛋糕、冰淇淋、牙膏里锁住水分；也是电子烟雾化液和舞台烟雾的主要成分。',
    en: 'A food-grade humectant that keeps cake, ice cream and toothpaste from drying out; it is also the main ingredient of vape liquid and stage fog.',
    itemsZh: ['食品与牙膏保湿', '化妆品与湿巾', '电子烟雾化液、舞台烟雾', '飞机除冰液'],
    itemsEn: ['Humectant in food and toothpaste', 'Cosmetics and wet wipes', 'Vape liquid and stage fog', 'Aircraft de-icing fluid'],
  },
  r134a: {
    zh: '取代氟利昂的第二代制冷剂，冰箱和汽车空调里最常见的一种。不再破坏臭氧层，但温室效应约为二氧化碳的 1400 倍，正被 R-1234yf 等替代。',
    en: 'The second-generation refrigerant that replaced CFCs, standard in fridges and car air conditioning. It spares the ozone layer, but warms about 1,400 times as much as CO2, so it in turn is being replaced.',
    itemsZh: ['汽车空调制冷剂', '家用冰箱与冷柜', '气雾剂抛射剂', '正被低温室效应制冷剂替代'],
    itemsEn: ['Car air-conditioning', 'Fridges and freezers', 'Aerosol propellant', 'Being phased down for the climate'],
  },
  butadiene: {
    zh: '合成橡胶的起点。丁苯橡胶做轮胎，ABS 塑料做乐高积木和家电外壳 —— 都从这个四碳分子开始。',
    en: 'Where synthetic rubber starts: styrene-butadiene rubber becomes tyres, and ABS becomes Lego bricks and appliance housings — all from this four-carbon molecule.',
    itemsZh: ['丁苯橡胶轮胎', 'ABS 塑料（积木、外壳）', '鞋底与胶管', '尼龙 66 的原料之一'],
    itemsEn: ['Styrene-butadiene tyres', 'ABS plastic', 'Shoe soles and hoses', 'A feedstock for nylon 66'],
  },
  isoprene: {
    zh: '天然橡胶的重复单元 —— 橡胶树的乳汁就是异戊二烯长链。它也是萜类香气的基本积木，薄荷醇、柠檬烯都由它拼成。',
    en: 'The repeating unit of natural rubber: latex from a rubber tree is long isoprene chains. It is also the building block of the terpenes, so menthol and limonene are assembled from it.',
    itemsZh: ['天然橡胶与合成聚异戊二烯', '医用手套与轮胎', '萜类香气分子的基本单元', '植物释放，参与森林气味'],
    itemsEn: ['Natural and synthetic rubber', 'Medical gloves and tyres', 'The building block of terpenes', 'Released by plants into forest air'],
  },
  benzoicacid: {
    zh: '常以苯甲酸钠的形式出现在配料表里，抑制霉菌和酵母。它只在酸性环境有效，所以你会在汽水、果汁和酱料里看到它，却很少出现在牛奶里。',
    en: 'Usually listed as sodium benzoate, holding back moulds and yeasts. It only works in acid, so it appears in fizzy drinks, juices and sauces but almost never in milk.',
    itemsZh: ['汽水与果汁防腐（苯甲酸钠）', '酱油、果酱等调味品', '化妆品与药品防腐', '合成苯酚与尼龙的原料'],
    itemsEn: ['Preserving soft drinks and juice', 'Sauces and jams', 'Cosmetics and medicines', 'Feedstock for phenol and nylon'],
  },
  terephthalicacid: {
    zh: '它与乙二醇缩聚就得到 PET —— 全世界每年几千万吨的矿泉水瓶、涤纶面料和食品托盘都是这两个分子拼出来的。PET 也是最容易回收的塑料之一。',
    en: 'Condensed with ethylene glycol it becomes PET: tens of millions of tonnes a year of water bottles, polyester fabric and food trays, all from these two molecules. PET is also among the easiest plastics to recycle.',
    itemsZh: ['PET 矿泉水瓶与饮料瓶', '涤纶（聚酯）衣物与被褥', '食品托盘与包装膜', '可回收再生为再生涤纶'],
    itemsEn: ['PET drink bottles', 'Polyester clothing and bedding', 'Food trays and films', 'Recycled back into fibre'],
  },
  salicylicacid: {
    zh: '柳树皮止痛的有效成分，也是阿司匹林的前身。它能溶解角质、疏通毛孔，所以祛痘产品、去屑洗发水和鸡眼贴里都有它。',
    en: 'The painkiller in willow bark and the parent of aspirin. It dissolves keratin and clears pores, which is why it turns up in acne products, anti-dandruff shampoo and corn plasters.',
    itemsZh: ['祛痘与水杨酸焕肤', '去屑洗发水', '鸡眼贴与去角质', '合成阿司匹林的原料'],
    itemsEn: ['Acne treatment and chemical peels', 'Anti-dandruff shampoo', 'Wart and corn plasters', 'The raw material for aspirin'],
  },
  methylsalicylate: {
    zh: '风油精、清凉油、红花油和肌肉贴布那股穿透力极强的气味。涂在皮肤上先觉得凉，再觉得热，然后局部抗炎镇痛 —— 但大量吞服有毒，一小瓶冬青油相当于很多片阿司匹林。',
    en: 'The piercing smell of muscle rubs, medicated oils and pain patches: cool first, then warm, then locally anti-inflammatory. Swallowed it is dangerous — a small bottle of wintergreen oil equals a great many aspirin tablets.',
    itemsZh: ['风油精、清凉油与红花油', '肌肉酸痛贴布与药膏', '牙膏与糖果的冬青香型', '注意：误服毒性很强'],
    itemsEn: ['Muscle rubs and medicated oils', 'Pain-relief patches', 'Wintergreen flavour', 'Highly toxic if swallowed'],
  },
  vanillin: {
    zh: '香草味的全部。冰淇淋、蛋糕、巧克力、香水里都是它；天然香草荚产量有限，市面上绝大部分香兰素由木质素或愈创木酚合成 —— 分子完全一样。',
    en: 'The whole of vanilla flavour, in ice cream, cake, chocolate and perfume. Natural pods cannot meet demand, so most vanillin is synthesised from lignin or guaiacol — the identical molecule either way.',
    itemsZh: ['冰淇淋、烘焙与巧克力', '香水与香薰', '掩盖药品的苦味', '从木质素合成（与天然分子相同）'],
    itemsEn: ['Ice cream, baking and chocolate', 'Perfume and scents', 'Masking bitterness in medicines', 'Synthesised from lignin'],
  },
  cinnamaldehyde: {
    zh: '肉桂的味道。它还是天然的抗菌剂 —— 古人用肉桂保存食物并非迷信。对昆虫有驱避作用，也被做成环保型驱虫剂。',
    en: 'The taste and smell of cinnamon, and a genuine antimicrobial — preserving food with cinnamon was never just superstition. It also repels insects, and is sold as a low-toxicity deterrent.',
    itemsZh: ['肉桂香料与烘焙', '口香糖与牙膏香型', '天然抗菌与食品保鲜', '环保型驱虫剂'],
    itemsEn: ['Cinnamon spice and baking', 'Chewing gum and toothpaste', 'Natural antimicrobial', 'Low-toxicity insect repellent'],
  },
  oxalicacid: {
    zh: '菠菜、苦瓜、竹笋的涩味来源之一。它和钙结合成不溶的草酸钙，既影响补钙，也是最常见肾结石的成分 —— 焯水就能去掉大部分。工业上是强力除锈剂和木材漂白剂。',
    en: 'Part of the astringency of spinach, bitter melon and bamboo shoots. With calcium it forms insoluble oxalate, which blocks calcium uptake and makes the commonest kidney stones — blanching removes most of it. Industrially it is a strong rust remover and wood bleach.',
    itemsZh: ['菠菜等蔬菜中的涩味（焯水可去）', '草酸钙肾结石的来源', '除锈剂与去污粉', '木材与织物漂白'],
    itemsEn: ['Astringency in leafy vegetables', 'Calcium-oxalate kidney stones', 'Rust and stain remover', 'Bleaching wood and fabric'],
  },
  citricacid: {
    zh: '柠檬酸味的来源，也是用量最大的食品酸味剂。它还能螯合金属离子，所以既能除水垢、洗衣服，也能防止果汁氧化变色。细胞里的三羧酸循环就以它命名。',
    en: 'The sourness of a lemon and the most-used food acidulant there is. It also grabs metal ions, so it descales kettles, boosts detergents and stops juice browning. The citric acid cycle in your cells is named for it.',
    itemsZh: ['汽水、糖果与果汁酸味剂', '除水垢与厨房清洁', '洗涤剂与柔顺剂助剂', '细胞三羧酸循环的中间体'],
    itemsEn: ['Acidulant in drinks and sweets', 'Descaling kettles and taps', 'Detergent builder', 'An intermediate of the citric acid cycle'],
  },
  ascorbicacid: {
    zh: '维生素 C。人类不能自己合成它，必须从食物摄取 —— 长期缺乏就是坏血病。食品工业也把它当抗氧化剂，切开的水果撒点它就不容易发褐。',
    en: 'Vitamin C. Humans cannot make it and must eat it — long-term shortage is scurvy. Industry also uses it as an antioxidant: a sprinkle keeps cut fruit from browning.',
    itemsZh: ['维生素 C 补充与防治坏血病', '合成胶原蛋白必需', '食品抗氧化护色剂', '促进植物性铁的吸收'],
    itemsEn: ['Vitamin C supplements', 'Needed to build collagen', 'Food antioxidant', 'Helps absorb iron from plants'],
  },
  xylitol: {
    zh: '无糖口香糖的甜味来源。口腔细菌不能发酵它，反而会被它抑制，所以它真的能减少蛀牙。溶解吸热带来清凉感；但它对狗有剧毒，务必收好。',
    en: 'The sweetener in sugar-free gum. Mouth bacteria cannot ferment it and are suppressed by it, so it genuinely reduces decay. Dissolving it absorbs heat, hence the cool taste — but it is severely toxic to dogs, so keep it away from them.',
    itemsZh: ['无糖口香糖与含片', '防蛀牙膏', '糖尿病人的代糖', '对狗有剧毒，需收好'],
    itemsEn: ['Sugar-free gum and mints', 'Anti-cavity toothpaste', 'A sugar substitute for diabetics', 'Severely toxic to dogs'],
  },
  glutamicacid: {
    zh: '鲜味的分子基础。它的钠盐就是味精，而昆布、番茄、干酪、火腿之所以鲜，也是因为蛋白质分解出了游离谷氨酸 —— 味精和高汤在舌头上是同一件事。',
    en: 'The molecule behind savoury taste. Its sodium salt is MSG, and kelp, tomato, cheese and ham taste savoury for the same reason: protein breaking down into free glutamate. On the tongue, MSG and stock are the same thing.',
    itemsZh: ['味精与鲜味调味料', '昆布高汤、番茄、干酪的鲜味', '人体主要的兴奋性神经递质', '蛋白质的组成氨基酸之一'],
    itemsEn: ['MSG and savoury seasonings', 'Umami in kelp stock, tomato and cheese', 'The brain’s main excitatory transmitter', 'One of the protein amino acids'],
  },
  stearicacid: {
    zh: '牛油、可可脂里的主要饱和脂肪酸。它和碱反应成肥皂，是最古老的化学工艺之一；蜡烛、乳霜、巧克力的口感也都靠它。',
    en: 'The main saturated fatty acid in tallow and cocoa butter. Treated with alkali it becomes soap — one of the oldest chemical processes there is — and it also gives candles, creams and chocolate their texture.',
    itemsZh: ['肥皂与洗涤用品', '蜡烛与蜡笔', '化妆品乳霜的增稠剂', '巧克力与可可脂的口感'],
    itemsEn: ['Soap and detergents', 'Candles and crayons', 'Thickener in creams', 'Texture in chocolate'],
  },
  oleicacid: {
    zh: '橄榄油约七成是它，也是"单不饱和脂肪"的代表。那个顺式弯折让分子堆不紧密，所以它常温下是液体、也比饱和脂肪更利于血脂。',
    en: 'About 70% of olive oil, and the archetype of a monounsaturated fat. The cis kink stops the molecules packing tightly, so it stays liquid at room temperature and treats blood lipids more kindly than saturated fat.',
    itemsZh: ['橄榄油、菜籽油与牛油果', '皮肤与头发的天然油脂成分', '肥皂与化妆品原料', '单不饱和脂肪的代表'],
    itemsEn: ['Olive and rapeseed oil', 'Natural skin and hair oils', 'Soap and cosmetics', 'The model monounsaturated fat'],
  },
  theobromine: {
    zh: '巧克力提神的主力，可可豆里含量远高于咖啡因。它作用温和而持久，还能舒张血管、镇咳。但狗和猫代谢它极慢，一块黑巧克力就可能致命。',
    en: 'What actually lifts you in chocolate — cocoa contains far more of it than caffeine. It works gently and for longer, relaxes blood vessels and suppresses coughs. Dogs and cats clear it very slowly, so a bar of dark chocolate can kill.',
    itemsZh: ['巧克力与可可制品', '温和持久的提神作用', '血管舒张与镇咳', '对猫狗有毒'],
    itemsEn: ['Chocolate and cocoa', 'A gentle, lasting lift', 'Vasodilator and cough suppressant', 'Toxic to cats and dogs'],
  },
  uricacid: {
    zh: '嘌呤代谢的终点。人体每天都在产生它，浓度过高就在关节里结晶 —— 痛风。海鲜、内脏、啤酒之所以被列为"高危"，正是因为嘌呤含量高。鸟类和爬行动物则用它排氮，几乎不耗水。',
    en: 'The end of purine metabolism. Your body makes it daily; too much and it crystallises inside a joint — gout. That is why shellfish, offal and beer are on the risk list. Birds and reptiles use it to excrete nitrogen almost without water.',
    itemsZh: ['痛风与高尿酸血症', '嘌呤（海鲜、内脏、啤酒）代谢终产物', '血中重要的抗氧化物', '鸟类与爬行类的排氮方式'],
    itemsEn: ['Gout and high urate', 'The end product of purine metabolism', 'A major antioxidant in blood', 'How birds and reptiles excrete nitrogen'],
  },
  dopamine: {
    zh: '奖赏与动机的神经递质，它编码的是"预期"而不是快乐本身 —— 短视频和老虎机让人停不下来，正是踩中了这个回路。帕金森病则源于产生多巴胺的神经元退化。',
    en: 'The transmitter of reward and motivation, encoding anticipation rather than pleasure itself — which is exactly what short-video feeds and slot machines exploit. Parkinson’s disease comes from the loss of the neurons that make it.',
    itemsZh: ['奖赏、动机与成瘾回路', '运动控制（帕金森病相关）', '临床用于升压强心', '注意力与学习'],
    itemsEn: ['Reward, motivation and addiction', 'Motor control and Parkinson’s', 'A clinical vasopressor', 'Attention and learning'],
  },
  adrenaline: {
    zh: '应急激素。危险来临时几秒内让心跳加快、血糖升高、支气管扩张，把身体切换到"战或逃"。也是过敏性休克的急救药 —— 肾上腺素笔能救命。',
    en: 'The emergency hormone: within seconds of danger it speeds the heart, raises blood sugar and opens the airways, switching the body to fight-or-flight. It is also the treatment for anaphylaxis — an adrenaline pen saves lives.',
    itemsZh: ['应激反应（战或逃）', '过敏性休克急救笔', '心脏骤停抢救用药', '局麻药中收缩血管延长药效'],
    itemsEn: ['The fight-or-flight response', 'Anaphylaxis auto-injectors', 'Cardiac arrest resuscitation', 'Added to local anaesthetics'],
  },
  ibuprofen: {
    zh: '布洛芬。退烧、止痛、消炎三件事一起做，牙痛、痛经、扭伤、发烧都常用。它抑制环氧合酶，代价是刺激胃黏膜，所以要饭后吃。',
    en: 'Fever, pain and inflammation all at once — toothache, period pain, sprains, a temperature. It blocks cyclo-oxygenase, and the price of that is stomach irritation, so it is taken with food.',
    itemsZh: ['退烧与止痛', '牙痛、痛经与运动损伤', '关节炎消炎', '需饭后服用，护胃'],
    itemsEn: ['Fever and pain relief', 'Toothache, period pain, sprains', 'Anti-inflammatory for arthritis', 'Taken with food to spare the stomach'],
  },
  menthol: {
    zh: '薄荷的清凉。它并不降温，只是打开了皮肤和口腔里的冷觉通道 TRPM8 —— 大脑被"骗"成觉得冷。牙膏、口香糖、清凉油、鼻通吸入剂都靠它。',
    en: 'The chill of mint. It does not lower any temperature; it simply opens TRPM8, the cold channel in skin and mouth, and the brain is fooled into feeling cold. Toothpaste, chewing gum, muscle rubs and inhalers all rely on it.',
    itemsZh: ['牙膏、漱口水与口香糖', '清凉油与薄荷膏', '鼻塞吸入剂与含片', '止痒与局部镇痛'],
    itemsEn: ['Toothpaste, mouthwash and gum', 'Cooling balms', 'Decongestant inhalers and lozenges', 'Anti-itch and topical pain relief'],
  },
  nicotine: {
    zh: '烟草成瘾的根源。吸入后约十秒到达大脑，激活乙酰胆碱受体并释放多巴胺，把"再来一根"写进奖赏回路。它本身也是烟草的天然杀虫剂，曾直接用作农药。',
    en: 'The reason tobacco is addictive: about ten seconds from lungs to brain, where it activates nicotinic receptors and releases dopamine, writing "one more" into the reward circuit. It is the plant’s own insecticide, and was once sprayed on crops as one.',
    itemsZh: ['香烟与电子烟的成瘾成分', '戒烟贴片与尼古丁口香糖', '烟草天然杀虫成分', '新烟碱类农药的原型'],
    itemsEn: ['The addictive part of tobacco and vapes', 'Patches and nicotine gum', 'The plant’s own insecticide', 'The model for neonicotinoid pesticides'],
  },
  fructose: {
    zh: '水果和蜂蜜里的糖，天然糖里最甜的一个。与葡萄糖组成蔗糖；果葡糖浆则让它大量进入饮料 —— 它几乎只在肝脏代谢，摄入过多与脂肪肝、尿酸升高有关。',
    en: 'The sugar of fruit and honey, and the sweetest natural sugar. Joined to glucose it makes sucrose; as high-fructose syrup it floods soft drinks — and because it is metabolised almost entirely in the liver, too much is linked to fatty liver and raised urate.',
    itemsZh: ['水果与蜂蜜的甜味', '果葡糖浆（饮料、烘焙）', '与葡萄糖组成蔗糖', '过量摄入与脂肪肝相关'],
    itemsEn: ['Sweetness of fruit and honey', 'High-fructose syrup in drinks', 'Half of every sucrose molecule', 'Excess is linked to fatty liver'],
  },
  sucrose: {
    zh: '白砂糖、冰糖、方糖都是它，从甘蔗和甜菜里提取。除了甜，它还负责焦糖化上色、抑制微生物（果酱和蜜饯正是靠高糖保存），以及在烘焙中保持湿润。',
    en: 'Table sugar, rock sugar and sugar cubes are all this one compound, pressed from cane and beet. Besides sweetness it caramelises for colour, holds back microbes — high sugar is how jam keeps — and keeps baking moist.',
    itemsZh: ['白砂糖与各类甜食', '果酱、蜜饯的高糖保存', '焦糖化与美拉德上色', '发酵酿酒的原料'],
    itemsEn: ['Table sugar in everything sweet', 'Preserving jam and candied fruit', 'Caramel colour and browning', 'Feedstock for fermentation'],
  },
  benzaldehyde: {
    zh: '苦杏仁味的来源，杏仁精、樱桃味糖果、部分香水都用它。杏核、桃核里的苦杏仁苷分解时会连带放出氰化氢，所以生食苦杏仁有风险。',
    en: 'The bitter-almond note in almond essence, cherry sweets and some perfumes. In apricot and peach kernels it is released together with hydrogen cyanide, which is why raw bitter kernels are risky to eat.',
    itemsZh: ['杏仁香精与烘焙调味', '樱桃、杏仁味糖果', '香水与日化香精', '合成染料与药物的中间体'],
    itemsEn: ['Almond essence in baking', 'Cherry and almond sweets', 'Perfume and household scents', 'Intermediate for dyes and drugs'],
  },
  isoamylacetate: {
    zh: '香蕉、梨的果香，食品香精里的常客，也用作胶水和指甲油的溶剂（俗称香蕉水）。蜜蜂用它当报警信息素，被蜇后招来更多同伴的就是这个味道。',
    en: 'The banana-and-pear note of food flavourings, and the solvent smell of some glues and nail varnish. Honeybees use it as an alarm pheromone — that smell is what calls the rest of the hive in.',
    itemsZh: ['香蕉、梨味食用香精', '胶水与指甲油溶剂', '蜜蜂报警信息素', '酯类"水果香"的典型代表'],
    itemsEn: ['Banana and pear flavouring', 'Solvent in glue and nail varnish', 'Honeybee alarm pheromone', 'The classic fruity ester'],
  },
  adipicacid: {
    zh: '尼龙 66 的两种单体之一，产量以百万吨计 —— 丝袜、地毯、安全带、渔线都从它开始。食品里也用作酸味剂，比柠檬酸更不吸潮，适合粉状饮料。',
    en: 'One of the two monomers of nylon 66, made by the million tonnes: stockings, carpet, seat belts, fishing line. It is also a food acidulant that, unlike citric acid, does not draw water — handy in powdered drinks.',
    itemsZh: ['尼龙 66 的原料', '聚氨酯与增塑剂', '粉状饮料与果冻的酸味剂', '润滑油与合成酯'],
    itemsEn: ['Raw material for nylon 66', 'Polyurethanes and plasticisers', 'Acidulant in powdered drinks', 'Synthetic lubricants'],
  },
  bisphenola: {
    zh: '聚碳酸酯（水壶、镜片、CD）和环氧树脂（罐头内涂层、地坪、胶）的原料，也用于热敏纸小票的显色。它能弱激活雌激素受体，因此婴童用品与许多水瓶已改用无 BPA 材料。',
    en: 'The building block of polycarbonate (bottles, lenses, CDs) and epoxy resin (can linings, floor coatings, glue), and the developer in thermal till receipts. It weakly activates the oestrogen receptor, so baby goods and many bottles have moved to BPA-free materials.',
    itemsZh: ['聚碳酸酯水壶与镜片', '罐头内涂层与环氧胶', '热敏纸小票', '内分泌干扰争议与"无 BPA"替代'],
    itemsEn: ['Polycarbonate bottles and lenses', 'Can linings and epoxy glue', 'Thermal receipt paper', 'The reason for BPA-free products'],
  },
  capsaicin: {
    zh: '辣椒的辣。辣不是味觉而是痛觉与热觉，所以喝水没用 —— 它不溶于水，要靠牛奶、酸奶或油脂带走。它也被做成镇痛膏药：反复刺激后神经末梢会对疼痛变迟钝。',
    en: 'The heat of chilli. Heat is a pain and temperature signal rather than a taste, and since capsaicin will not dissolve in water, drinking water does nothing — milk, yoghurt or oil carries it away. It is also made into pain-relief patches: repeated stimulation leaves nerve endings less responsive to pain.',
    itemsZh: ['辣椒的辣味（TRPV1 痛觉通道）', '镇痛贴与关节痛药膏', '防身喷雾的有效成分', '驱鸟不驱兽的天然屏障'],
    itemsEn: ['The burn of chilli, via TRPV1', 'Pain-relief patches and creams', 'The active agent in pepper spray', 'A plant defence that birds ignore'],
  },
}
