import type { MoleculeGeometry } from '../types/molecule'
import raw from './moleculeGeometry.json'

/**
 * Atom coordinates and bonds, generated by scripts/build-molecules.mjs.
 *
 * Import this from the 3D viewer only. It is more than half of the molecule data
 * and nothing else needs it, so keeping it out of every other module is what keeps
 * it inside the lazily-loaded viewer chunk rather than the initial bundle.
 */
const GEOMETRY = raw as unknown as Record<string, MoleculeGeometry>

export function moleculeGeometry(id: string): MoleculeGeometry {
  const geometry = GEOMETRY[id]
  if (!geometry) throw new Error(`No geometry for molecule "${id}"`)
  return geometry
}
